### ISSUE TITLE
Idea for improvement

### ISSUE THREAD

**Issue by GiorgioBarnabo** [jdepoix/youtube-transcript-api#104]
Hi there,

thank you for this amazing project! It is definitely very helpful ;)
Here's a little advice for improvement. 
When calling the YouTubeTranscriptApi.get_transcript function,
it would be cool if the search considered automatically generated
and automatically translated transcripts. 
For example, given a language, it would be great if the function returned:
- a manually created transcript when available
- a automatically generated transcript if a manually created one is not available
- a translated transcript when both previous points fail

Thank again.

Best,

Giorgio

**Comment by jdepoix** [comment]
Hi @GiorgioBarnabo,
that actually is exactly what `get_transcript` does except for the translation part. I do not think it should automatically translate without the user asking for it. You could however easily implement this using `list_transcripts` if that behaviour is desired in your usecase.
