### ISSUE TITLE
Subtitles are disabled for this video

### ISSUE THREAD

**Issue by shwetankshot12** [jdepoix/youtube-transcript-api#110]
youtube_transcript_api._errors.TranscriptsDisabled:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=Eto_2_VKJRI! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at
https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!

PPPPPPPPPPPLLLLLLLEEEEEEEASSSSSSSSEEEEEEEEEE HEEEEEEEEELPPPPPPPPPPPP

i used this code in visual studio code and my python was installed from cmd whereas VSC was installled in D directory. the issue is i wrote this code and with the terminal in VSC executed the same python project file.

from youtube_transcript_api import YouTubeTranscriptApi
srt=YouTubeTranscriptApi.get_transcript('Eto_2_VKJRI')
with open('srt_file.txt','w') as f: 
    for i in srt:
        f.write('%s\n' % i)

**Comment by jdepoix** [comment]
As the error message correctly indicates, subtitles are disabled for this video. If the uploader disables subtitles for his video there's nothing you can do about this.

**Comment by shwetankshot12** [comment]
but the option of open transcript option is available on youtube..under the same youtube video..so how sbtitles r disabled for the video

**Comment by jdepoix** [comment]
But what happens when you press that button? For me it just opens the transcript window and a spinner loads forever without a transcript ever appearing. I don't know why YouTube shows this under options even though transcripts are disabled, but you can also tell they are disabled because there is no subtitle button in the video player.

**Comment by balla-a** [comment]
For this video, I get this error, but it seems it has a transcript. https://www.youtube.com/watch?v=4FN12sqoC4Y
ran the code: YouTubeTranscriptApi.get_transcript('4FN12sqoC4Y',languages=['en'])
Any idea why? I also ran this code like 100 videos, and 5 of them lead to the same error.

**Comment by jdepoix** [comment]
@balla-a it seems that the video `4FN12sqoC4Y` is age restricted. Read https://github.com/jdepoix/youtube-transcript-api#cookies to learn how to work around this.

I also created a new Issue (#111) to provide a more descriptive error message when accessing age restricted videos.

**Comment by xenova** [comment]
> @balla-a it seems that the video `4FN12sqoC4Y` is age restricted. Read https://github.com/jdepoix/youtube-transcript-api#cookies to learn how to work around this.
> 
> I also created a new Issue (#111) to provide a more descriptive error message when accessing age restricted videos.

Just a heads up, but it still appears that you can view the transcript of a video, even if it's age restricted:
![image](https://user-images.githubusercontent.com/26504141/145359100-ba6a1ee5-43b9-48f1-ba6b-64f69a2e984a.png)

There's most likely a workaround that exists to generate the correct parameters when loading the transcript.

**Comment by jdepoix** [comment]
@xenova huh, that's interesting. I will have to take a deeper look into this to see if the response still contains the information we need to parse the transcript URLs as we currently do.

**Comment by jdepoix** [comment]
@crhowell sounds interesting. I will have to look into this when I got a bit more time to spare. Just to clarify: what do you mean by `INNERTUBE_API_KEY`?

**Comment by crhowell** [comment]
@jdepoix The HTML returned back to the `_extract_captions_json` method. If you were to inspect it you should find each of those KEYS ( _INNERTUBE_API_KEY_, _INNERTUBE_CLIENT_NAME_, etc.)  buried within script tags.
