### ISSUE TITLE
YouTube is receiving too many requests from this IP

### ISSUE THREAD

**Issue by cantwbr** [jdepoix/youtube-transcript-api#112]
I receive the `TooManyRequests` exception from different IP addresses when I execute:

`YouTubeTranscriptApi.list_transcripts("WH8I15Cxwss")`

I checked for a captcha using both Firefox and Chrome from these IP addresses, but was not asked to solve one.

I am using youtube-transcript-api 0.4.1 and Python 3.7.7

```
raise TooManyRequests(video_id)
youtube_transcript_api._errors.TooManyRequests: 
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=WH8I15Cxwss! This is most likely caused by:

YouTube is receiving too many requests from this IP and now requires solving a captcha to continue. One of the following things can be done to work around this:
        - Manually solve the captcha in a browser and export the cookie. Read here how to use that cookie with youtube-transcript-api: https://github.com/jdepoix/youtube-transcript-api#cookies
        - Use a different IP address
        - Wait until the ban on your IP has been lifted

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
```

**Comment by jdepoix** [comment]
Hi @cantwbr,

unfortunately, I was never able to replicate this myself, but users have reported that they were able to work around this by solving a captcha. It could very well be that this is not a reliable solution, this was more added as "a thing you could try" to this error message. Unfortunately, there isn't too much you can do to work around YouTubes rate limits other than changing your IP.
