### ISSUE TITLE
Problem The video is no longer available

### ISSUE THREAD

**Issue by CamilleSchr** [jdepoix/youtube-transcript-api#118]
Hi,

I would have to have the transcriptions of the videos of one channel.
I followed this tuto : https://www.pragnakalp.com/automate-youtube-video-transcription-python/
on the channel id : UCg40OxZ1GYh3u3jBntB6DLg (Forbes Breaking News)

And I have this result for all the videos on this channel : 

_Could not retrieve a transcript for the video https://www.youtube.com/watch?v=aiB5zgNWgwU! This is most likely caused by:
The video is no longer available
If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!_

But the video is still available on youtube : https://www.youtube.com/watch?v=aiB5zgNWgwU!

I use youtube_transcript_api-0.3.1

Can you help me please ?

Thanks,
Cheers, 
Camille

**Comment by jdepoix** [comment]
Hi @CamilleSchr, try updating to v0.4.1, that will most likely fix your problem.

**Comment by CamilleSchr** [comment]
Thanks it works with the new version :)
