### ISSUE TITLE
Get transcriptions of playlist videos

### ISSUE THREAD

**Issue by CamilleSchr** [jdepoix/youtube-transcript-api#119]
Hi,

I would like to get the transcription of this channel (explore>news>worldnews) : https://www.youtube.com/channel/UCvAvFl2OGsuDSoOo93Kd0nA

I follow this tuto and put channel_id= 'UCvAvFl2OGsuDSoOo93Kd0nA', but I received this following error :

_HttpError: <HttpError 404 when requesting https://youtube.googleapis.com/youtube/v3/playlistItems?playlistId=UUvAvFl2OGsuDSoOo93Kd0nA&part=snippet&maxResults=50&key=myapikey&alt=json returned "The playlist identified with the request's <code>playlistId</code> parameter cannot be found.". Details: "[{'message': "The playlist identified with the request's <code>playlistId</code> parameter cannot be found.", 'domain': 'youtube.playlistItem', 'reason': 'playlistNotFound', 'location': 'playlistId', 'locationType': 'parameter'}]">_

Can you help me please ? Is it because this page https://www.youtube.com/channel/UCvAvFl2OGsuDSoOo93Kd0nA use a lot of playlist, with videos of others channels ?

Thanks,
Cheers,
Camille

**Comment by jdepoix** [comment]
Hi @CamilleSchr, it seems like you're asking a question about YouTubes public API. That doesn't have anything to do with this module. Please refer to the official documentation.
