### ISSUE TITLE
Could not get available persian subtitle

### ISSUE THREAD

**Issue by hosnas** [jdepoix/youtube-transcript-api#12]
simply I'm doing the following command in cli
`youtube_transcript_api LKvjIsyYng8 --languages fa
`
However I cant get the language I want that is available in subtitles.

**Comment by utkarshdubey** [comment]
That would probably be a problem with the captions. If the caption is not
available for a particular language, it can't be fetched along.

**Comment by hosnas** [comment]
@utkarshdubey  as I said, the caption is available. But its not being fetched.

**Comment by utkarshdubey** [comment]
Could you give me more information or the Tracebacks if you received any
errors?

**Comment by hosnas** [comment]
@utkarshdubey  the only error I'm getting is this:

`ERROR:youtube_transcript_api._api:Could not get the transcript for the video https://www.youtube.com/watch?v=LKvjIsyYng8! Most likely subtitles have been disabled by the uploader or the video is no longer available.
{}
`
Although its clearly not correct. cause I can pick `fa` language from list of subtitles by clicking on  `persian`

**Comment by jdepoix** [comment]
@hosnas I can not replicate this error.

Running `youtube_transcript_api LKvjIsyYng8 --languages fa` with the current version (0.1.4) prints the subtitles without errors, using python 2 and 3.

Could you please provide more information on the version of youtube-transcript-api and the version of python you are using?

**Comment by hosnas** [comment]
@jdepoix very wierd. I changed my location in youtube pannel and was able to get the subtitle.

**Comment by jdepoix** [comment]
@hosnas so would you consider your problem to be solved, or should we investigate further?

**Comment by hosnas** [comment]
@jdepoix  yes im considering it solved
