### ISSUE TITLE
Enable Curse Words

### ISSUE THREAD

**Issue by Lavarider** [jdepoix/youtube-transcript-api#120]
First off, thanks for the library, it has worked very well and helped me a great deal. 

However, while looking through the transcripts for some videos (Michael Reeves for context), I noticed that "[ __ ]" was in the place where I assume curse words would be located.  Is there any way to get curse words to show up in these locations? I am using the basic get_transcript command.

**Comment by jdepoix** [comment]
Hi @Lavarider, actually I never notices this. Could you maybe share the ID of a video where this is the case? Does YouTube also show it like that when you enable subtitles on their Web-Player?

Without having this tested, I could imaging that YouTube censors curse-words when not being logged in (or logged in and under 18 or something like that). So maybe if you use a cookie from a logged in session you'll get uncensored subtitles. [Check this out to find out how to use cookies](https://github.com/jdepoix/youtube-transcript-api#cookies).
Would be great if you could provide some feedback whether this works or not! 👍

**Comment by Lavarider** [comment]
One video where this is the case is "I built a Surgery Robot" at this link: https://www.youtube.com/watch?v=A_BlNA7bBxo. The closed captions between 1 minute and 1:10 are probably the most helpful for reference.

Youtube does have this "feature" when I enable subtitles on their web player. However, this is always enabled in the web player closed captions, both when I try and watch youtube signed out and when I signed in on an account registered as 30 years old. This leads me to believe changing cookies won't do much. Additionally, this Reddit post: https://www.reddit.com/r/youtube/comments/iurox3/youtube_literally_censoring_swears_in/ implies this is a problem for everyone.

**Comment by jdepoix** [comment]
Wow, looks like you're right. There actually seems to be no way to get an uncensored transcripts. That's kinda ridiculous 😄 
But unfortunately if there's no way to get these transcripts in the web-player, then there's also no way to get them with this module 😞 
So I'll unfortunately have to close this as there is not much we can do here.
