### ISSUE TITLE
TranscriptsDisabled: Subtitles are disabled for this video

### ISSUE THREAD

**Issue by jyotsna2893** [jdepoix/youtube-transcript-api#123]
https://www.youtube.com/watch?v=_0pRQtpA7iY&ab_channel=FormulaWorld

I was trying to get text from this video. Transcript failed, stating that subtitles are off for this video. It happened earlier also where subtitles where enabled and it still failed.

**Comment by jdepoix** [comment]
Please provide the exact code you are executing and error message you are receiving while doing so.

**Comment by jdepoix** [comment]
@jyotsna2893 is this still relevant? Please let me know if your issues has been resolved, so that I can close this issue.

**Comment by jyotsna2893** [comment]
Hello, I did not encounter that error again. So, yes you can close the
issue for now.
