### ISSUE TITLE
subtitles seem enabled, but do not load

### ISSUE THREAD

**Issue by epogrebnyak** [jdepoix/youtube-transcript-api#124]
Thank you very much for maintianing youtube-transcript-api!

I got stuck with subtutles that do not load, even though I enabled them in video, and switched of content under 18 flag for video and the channel. Maybe these changes take a while to take effect, but I do see subtitles in video.

I try the following code:

```python
from youtube_transcript_api import YouTubeTranscriptApi as YT
video_id = "oUzcoYAwYyI"
YT.get_transcripts(video_id, languages=['ru'])
```

it fails with:

```
  File "tc.py", line 3, in <module>
    YT.get_transcripts(video_id, languages=['ru'])
  File "C:\Users\epogr\Anaconda3\lib\site-packages\youtube_transcript_api\_api.py", line 102, in get_transcripts

    raise exception
  File "C:\Users\epogr\Anaconda3\lib\site-packages\youtube_transcript_api\_api.py", line 99, in get_transcripts
    data[video_id] = cls.get_transcript(video_id, languages, proxies, cookies)
  File "C:\Users\epogr\Anaconda3\lib\site-packages\youtube_transcript_api\_api.py", line 128, in get_transcript
    return cls.list_transcripts(video_id, proxies, cookies).find_transcript(languages).fetch()
  File "C:\Users\epogr\Anaconda3\lib\site-packages\youtube_transcript_api\_api.py", line 70, in list_transcripts

    return TranscriptListFetcher(http_client).fetch(video_id)
  File "C:\Users\epogr\Anaconda3\lib\site-packages\youtube_transcript_api\_transcripts.py", line 36, in fetch
    self._extract_captions_json(self._fetch_video_html(video_id), video_id)
  File "C:\Users\epogr\Anaconda3\lib\site-packages\youtube_transcript_api\_transcripts.py", line 48, in _extract_captions_json
    raise TranscriptsDisabled(video_id)
youtube_transcript_api._errors.TranscriptsDisabled:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=o! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
```

**Comment by epogrebnyak** [comment]
Minor note the address is `https://www.youtube.com/watch?v=o!` - something got cut from the error message, the id is oUzcoYAwYyI

**Comment by epogrebnyak** [comment]
I reviewed #123 and #100 for ideas to fix, but so far it is to look at child control, which I tried.

**Comment by jdepoix** [comment]
Hi @epogrebnyak, `get_transcripts` takes an `Iterable` of video IDs. So if you pass in a single string containing a video id it will iterate through each character of that string considering it a video id. You'll have to either do
```python
YT.get_transcripts([video_id], languages=['ru'])
```
or
```python
YT.get_transcript(video_id, languages=['ru'])
```

I think a few people have stumble over this, as `get_transcripts` gets easily confused with `get_transcript`. I think I will add an `assert` to `get_transcripts` to make sure the passed in video id param is not a string, to make the mistake more obvious.

**Comment by jdepoix** [comment]
I opened an issue to add that assert in the future.

**Comment by epogrebnyak** [comment]
Thank you for clarifying, indeed easily confused. 

Have you considered a more object-like interface Video(youtude_id).get_transcript()? This is really a sugar over existing API, but maybe useful.

**Comment by jdepoix** [comment]
@epogrebnyak the static methods `get_transcript` and `get_transcripts` really only are convenience-wrappers around the `TranscriptList` object. Look at [this example if you want to use `TranscriptList` objects instead](https://github.com/jdepoix/youtube-transcript-api#by-example), which give you more options.
