### ISSUE TITLE
hello world sandbox on repl.it

### ISSUE THREAD

**Issue by 100ideas** [jdepoix/youtube-transcript-api#129]
Hi, thanks for this useful package!

I played around with it a bit today on repl.it. Maybe should have written a new custom Formatter but instead I just hacked together some string processing. 

Anyway, if anyone wants a quick way to play with this library, here's the repl.it instance 

https://replit.com/@100ideas/youtube-transcript-apitest

and repo

https://github.com/100ideas/-youtube-transcript-api_replit

thanks again! would be cool to host this on a free serverless host somewhere... hmm

**Comment by jdepoix** [comment]
Hi @100ideas, thank you for sharing this!
However, the purpose of GitHub's Issue section mainly is to report on bugs in this module and discuss new features. Therefore, this probably isn't the right place to share this information. GitHub recently added a [Discussion section](https://github.com/jdepoix/youtube-transcript-api/discussions), which has been used by a few people to discuss stuff, which doesn't really fit into an issue. So I guess that probably would be a better place to share your work 👍
