### ISSUE TITLE
Get confused at the format "webvvt"

### ISSUE THREAD

**Issue by MAJA-Lin** [jdepoix/youtube-transcript-api#134]
I thought this might be a typo?

https://github.com/jdepoix/youtube-transcript-api/blob/5657a4867476d6edae582b7de3a07e395128b964/youtube_transcript_api/formatters.py#L138-L144

REF: [Web Video Text Tracks Format (WebVTT)](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API)

**Comment by jdepoix** [comment]
Oh boy, you are right! How did this go unnoticed for so long... 🙈 
Thanks for pointing this out!
