### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /watch?

### ISSUE THREAD

**Issue by BMouhcine** [jdepoix/youtube-transcript-api#138]
Hello,
I am using youtube-transcript-api and this error is thrown from time to time.
`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /watch?v=N1pseW9waNI (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2148e536d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))`

I've also added a time.sleep(2.4) (politeness delay of 2.4s between two requests) but this doesn't solve the problem.
PS: When I get the error, I wait approx. 20mn and I send the request, it works, and just after, the error thrown, and so forth..

The line producing the error is : `transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)`

Whole ERROR logs: 

[logs.txt](https://github.com/jdepoix/youtube-transcript-api/files/7648869/logs.txt)

Your help is appreciated ! :-)) thanks

**Comment by jdepoix** [comment]
Hi @BMouhcine, while running into rate limits with YouTube isn't uncommon, I haven't seen that particular error yet. It does seem more like it's a networking problem in your stack. What machine is this code running on? And what OS and python version are you using?

**Comment by BMouhcine** [comment]
> Hi @BMouhcine, while running into rate limits with YouTube isn't uncommon, I haven't seen that particular error yet. It does seem more like it's a networking problem in your stack. What machine is this code running on? And what OS and python version are you using?

Hello @jdepoix , thanks for answering :-)
Windows & Docker (Docker Desktop in Windows), the error persists in both systems.
I'm currently using python3.8 with youtube-transcript-api==0.4.2.
The error is also thrown on MacOS (Docker Desktop).

Thanks !

**Comment by jdepoix** [comment]
Could you maybe check if you are able to do any of the following requests directly after `YouTubeTranscriptApi.list_transcripts` has failed and report back:
```python
try:
  requests.get('https://www.google.com').raise_for_status()
except:
  print('google failed')
try:
  requests.get('https://youtube.com').raise_for_status()
except:
  print('youtube failed')
try:
  requests.get('https://www.youtube.com').raise_for_status()
except:
  print('www.youtube.com failed')
```

**Comment by BMouhcine** [comment]
Hello @jdepoix , 
Here's the report back: 
`WARNING:root:youtube failed

WARNING:root:www.youtube.com failed`
PS: As I am in production mode, I did logging.warning instead of print

**Comment by jdepoix** [comment]
How about `ping`ing or `curl`ing (https://)youtube.com after the failure?

**Comment by BMouhcine** [comment]
`curl https://youtube.com` doesn't return anything. (as for https://facebook.com).  
However, `ping youtube.com` works.

**Comment by jdepoix** [comment]
I'm sorry, you'll have to run `curl https://www.youtube.com` for it to return anything

**Comment by BMouhcine** [comment]
Hello @jdepoix . Thanks for your time on this.
I ran `curl https://www.youtube.com`; It returns html, js. (I presume it's the source code of the page).

**Comment by jdepoix** [comment]
So even while the error is occurring, you are able to curl youtube?
If so, please also do `curl "https://www.youtube.com/watch?v=VIDEOID"` with the video id which is failing and upload the response somewhere so that I can have a look at it.

**Comment by BMouhcine** [comment]
Hello @jdepoix . 
Something new: 
I tried to curl the youtube video link, then result returned is this. (I've tried to curl youtube & google as well).
  
![image](https://user-images.githubusercontent.com/44417293/145017663-3ae5ea85-303e-4afc-9e6f-4aa0afe2e084.png)

**Comment by jdepoix** [comment]
That is more the kind of result I expected. Unfortunately though, I don't think there is much I can help you with here. If your machine isn't even able to curl YouTube, there isn't much that YouTube Transcript API can do, to work around this.
Maybe there is something in your networking stack which is causing this problem, but it also could be that YouTube is blocking your requests. In the later case there isn't really anything you can do other than changing your IP address. In the first case you'll probably have to debug that yourself, as this is really hard to do without being able to play around on your infrastructure and quite frankly this is a bit out of the scope of this module.
Sorry, I can't help here! I will close this issue for now, but feel free to share more information for future readers if you happen to find a solution for your specific problem.
