### ISSUE TITLE
get_transcript returning 3 copies of each dictionary

### ISSUE THREAD

**Issue by sali0** [jdepoix/youtube-transcript-api#14]
Hello, and thank you for releasing this package, it is awesome. 

I have a problem when trying to concatenate all of the text to create a full text copy of the transcript. When I loop through the transcript returned by get_transcript, I get 3 copies of each dictionary. Here is my code:

```
with open(filename, 'r') as event:
    parsed_event = json.load(event)
    url_data = parse_qs(parsed_event["url"])
    video_id = url_data[next(iter(url_data))][0] # gets video id from youtube url
    transcript = transcriptor.get_transcript(video_id, languages=['en'])

  print(transcript)
```
with transcriptor being the YouTubeTranscriptApi.

My output looks like this:

> ...{'text': 'They kill babies too young to be vaccinated.', 'start': 604.545, 'duration': 3.101}, {'text': 'They kill babies too young to be vaccinated.', 'start': 604.545, 'duration': 3.101}, {'text': 'They kill babies too young to be vaccinated.', 'start': 604.545, 'duration': 3.101}, {'text': 'They kill healthy children that are just unlucky.',
'start': 607.981, 'duration': 3.102}, {'text': 'They kill healthy children that are just unlucky.', 'start': 607.981, 'duration': 3.102}, {'text': 'They kill healthy children that are just unlucky.', 'start': 607.981, 'duration': 3.102}, {'text': 'They bring serious diseases back\nfrom the verge of extinction.', 'start': 611.718, 'duration': 3.836}, {'text': 'They bring serious diseases back\nfrom the verge of extinction.', 'start': 611.718, 'duration': 3.836}, {'text': 'They bring serious diseases back\nfrom the verge of extinction.', 'start': 611.718, 'duration': 3.836}, {'text': 'And, the biggest side effect\nof vaccines is fewer dead children.', 'start': 615.923, 'duration': 4.336}, {'text': 'And, the biggest side effect\nof vaccines is fewer dead children.', 'start': 615.923, 'duration': 4.336}, {'text': 'And, the biggest side effect\nof vaccines is fewer dead children.', 'start': 615.923, 'duration': 4.336}, {'text': 'Vaccines are one of\nthe most powerful tools we have', 'start': 620.761, 'duration': 3.403}, {'text': 'Vaccines are one of\nthe most powerful tools we have', 'start': 620.761, 'duration': 3.403}, {'text': 'Vaccines are one of\nthe most powerful tools we have', 'start': 620.761, 'duration': 3.403},...

Do you know of this issue? Thank you!

**Comment by utkarshdubey** [comment]
Hey @sali0 ,
I am not able to understand what you are asking, but as far as I can guess, you may be wanting to just print the text field right? If that is the case, you can select the text field easily using ``transcript['text']``.
This will only print the text field and omit others such as start and duration. Similarly, if you want to access the latter, you can do it with ``transcript['fieldName']``.

**Comment by jdepoix** [comment]
Hi,

I need a bit more information to be able to replicate this: could you please provide the video ID of the video you are trying to get the subtitles for? And do you also have the problem if you just execute `YouTubeTranscriptApi.get_transcript('insert_video_id_here', languages=['en'])` without the other part of your code? Can you replicate the problem with other video IDs?

**Comment by sali0** [comment]
`{
  "url": "https://www.youtube.com/watch?v=zBkVCpbNnkU"
}`

That is the JSON I am feeding it. However, I just tried another video and it did work. Thank you for the quick reply.
