### ISSUE TITLE
stopped working 

### ISSUE THREAD

**Issue by jbrek** [jdepoix/youtube-transcript-api#153]
It stopped working few days ago.  I never get any results.  downloadyoutubesubtitles dot com also not working.

**Comment by jdepoix** [comment]
Hello @jbrek,
could you please provide more information
- which version of this module/python are you running?
- what exactly are you executing and what exactly is happening?

**Comment by jbrek** [comment]
youtube-transcript-api 0.4.4
It working today.  No clue what happened or changed but it works today!
