### ISSUE TITLE
close caption vs transcript?

### ISSUE THREAD

**Issue by BillionShields** [jdepoix/youtube-transcript-api#155]
Interesting case. Video is fresh so transcript is not yet available but closed captions CC are. Is there a way to get those?

**Comment by jdepoix** [comment]
Hi @BillionShields,
just to clarify: you mean that you can already enable subtitles on the YouTube's web player but when querying the transcript with this module you get an error?
It seems rather unlikely, as this module uses the same API endpoints the web player does, but maybe the request done by your `youtube-transcript-api` code was answered by a different node than the request done by your browser and that node wasn't up to date yet (the nature of eventually consistent systems). I haven't encountered that myself and its a bit tricky to test out. Do you have a usecase were this is a problem, or just something your were curious about?

**Comment by jdepoix** [comment]
closed due to inactivity
