### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by Botami143** [jdepoix/youtube-transcript-api#158]
Hello @jdepoix

how to use this tool please give me Idea

**Comment by jdepoix** [comment]
Hello @Botami143 

please read the [README](https://github.com/jdepoix/youtube-transcript-api#readme) to find out how to use this module.

**Comment by Botami143** [comment]
no working 
![Screenshot 2022-08-06 194021](https://user-images.githubusercontent.com/77289273/183252520-9cf816ca-7ee0-4423-b2d5-73e7165e08d5.png)

**Comment by jdepoix** [comment]
Just read the error message, it already explains why it is not working: the subtitles for this video are disabled, therefore, this module can't retrieve them.
