### ISSUE TITLE
youtube_transcript_api._errors.NoTranscriptFound

### ISSUE THREAD

**Issue by chirag127** [jdepoix/youtube-transcript-api#159]
https://www.youtube.com/watch?v=0pdV6icQt8M have the subtitle for "en" but still getting For this video (0pdV6icQt8M) transcripts are available in the following languages:

(MANUALLY CREATED)
 - en ("English")[TRANSLATABLE]

**Comment by jdepoix** [comment]
Hi @chirag127, could you maybe elaborate a bit more on what the problem is here, I am not sure if I am understanding you correctly. To me, it sounds like you want to get the English transcript, and as your log shows it actually is available. So what is missing?

**Comment by chirag127** [comment]
Resolved
