### ISSUE TITLE
vtt format error:  second must be in 0..59

### ISSUE THREAD

**Issue by zxl777** [jdepoix/youtube-transcript-api#160]
vtt format error:  
second must be in 0..59

<img width="365" alt="image" src="https://user-images.githubusercontent.com/816448/187822750-474190c3-ab86-4644-b8ac-f53b4559d49b.png">

source
https://www.youtube.com/watch?v=Jkdnn6klg7w

**Comment by jdepoix** [comment]
Hi @zxl777, thanks for reporting!

**Comment by jdepoix** [comment]
Fixed in [v0.5.0](https://github.com/jdepoix/youtube-transcript-api/releases/tag/v0.5.0) thanks to @liamrs222!
