### ISSUE TITLE
the right timestamp formation is '00:00:06,930' not '00:00:06.930'

### ISSUE THREAD

**Issue by lionderful** [jdepoix/youtube-transcript-api#162]
"," in srt timestamp format, not "."

_seconds_to_timestamp should return "{:02.0f}:{:02.0f}:{:02.0f},{:03d}".format(hours, mins, secs, ms)

thank you, man. you have done a great help for me,

**Comment by jdepoix** [comment]
Hi @lionderful, we currently only have a WebVTT formatter, for which this format is correct. But as I see you already contributed a SRT formatter 🥳
