### ISSUE TITLE
Generating transcripts using YouTube-transcript-api

### ISSUE THREAD

**Issue by rohitsanam** [jdepoix/youtube-transcript-api#165]
I am having video id's for multiple videos of a playlist when I am trying to extract th transcript I am getting the following error:

TranscriptsDisabled: 
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=b! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!

version of YouTube-transcript-api:0.4.4

**Comment by jdepoix** [comment]
Hello @rohitsanam, please supply the code you are executing. My guess is, that you are using `get_transcripts` instead of `get_transcript`. When using `get_transcripts` you need to pass in a list of strings and when using `get_transcript` you must pass in a string.

**Comment by jdepoix** [comment]
closed due to inactivity
