### ISSUE TITLE
Error - Request to YouTube Failed

### ISSUE THREAD

**Issue by wwestfall91** [jdepoix/youtube-transcript-api#183]
I am getting the following error when trying to hit the transcript API:

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
We Got Each Other The Worst Holiday Gifts (Live Audience!) - H3 Podcast #263 skipped - 
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.youtube.com/watch%3Fv%3Dvq8nR2LMrno&q=EhAmAQQCRAAvYJCHdWWTeJkvGIbcgJ8GIjBxTzdM3QaP-46VMgRUoFRI4DzGgJwtf4FSvFRaIRr8T0fHkzH_KjRnsha9k0XvpyUyAXI! This is most likely caused by:

Request to YouTube failed: vq8nR2LMrno

My program was working fine yesterday, and I haven't made any changes since then.

Let me know of you need any additional information from me.

**Comment by jdepoix** [comment]
Hi @wwestfall91,

the error is already in the error message: `Client Error: Too Many Requests for url`. There are plenty of threads on this issue. You can find more information here: https://github.com/jdepoix/youtube-transcript-api/discussions/176

I will close this now, as there is nothing we can do here.
