### ISSUE TITLE
choose language on youtubetranscript

### ISSUE THREAD

**Issue by KaterTom** [jdepoix/youtube-transcript-api#185]
Hi there,
I use https://youtubetranscript.com/ to get the transcription, which works great with English. 
Does anybody know, if there is something I could add to this url, if the default language of a video is English, but I want the ITALIAN transcript, which is also listed in the video as an option?
Similar question: What to add to the url when the default language is ITALIAN to begin with?

Should this not be possible → are there other websites that can handle this?
Thank you!
Tom

**Comment by jdepoix** [comment]
Hi @KaterTom,
I have no affiliation with that website, so I can't give you any support on how to use it. It might be using this module under the hood. If so, there probably isn't anything you can add to the URL to change the language, as they will probably parse out only the video id.
However, you can simply use this module directly to retrieve transcripts in whatever language you like. [Have a look at the documentation](https://github.com/jdepoix/youtube-transcript-api#readme) to find out how to use it. This is a standard use case, which is fairly well documented.

I will close this issue now, as there is nothing to do here.
