### ISSUE TITLE
CouldNotRetrieveTranscript Error for unknown reason.

### ISSUE THREAD

**Issue by julianbarg** [jdepoix/youtube-transcript-api#19]
Package works great. I tried a couple of URLs and came across an exception for this one:

https://www.youtube.com/watch?v=C8rRqRoCUsg

**Comment by jdepoix** [comment]
Hi @julianbarg,
thanks for reporting!
This actually turned out to be a bug, which I haven't encountered so far. However, it was easy to fix. The fix is implemented in #20.

**Comment by jdepoix** [comment]
@julianbarg just released v0.1.7, which should solve your problem!
