### ISSUE TITLE
It leaves spaces in some languages 

### ISSUE THREAD

**Issue by FurkanGozukara** [jdepoix/youtube-transcript-api#195]
I have used the python code to translate files

video id m-UVVY_syP0

for example in Turkish file it has extra spaces which causes errors

![image](https://user-images.githubusercontent.com/19240467/227066888-bd63b6ea-e6c4-4fcd-994a-65c2748fa0d6.png)

vtt format

which format is best? 

maybe you can auto remove such empty lines?

**Comment by jdepoix** [comment]
@FurkanGozukara Any updates here? Otherwise, I will close this issue as I can not replicate this.

**Comment by jdepoix** [comment]
Closed due to inactivity
