### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by lovetcodes** [jdepoix/youtube-transcript-api#196]
The transcript API works great on my local Flask server, but consistently fails in my hosted environment (onrender).

Error:
Could not retrieve a transcript for the video https://
www.youtube.com/watch?v=429 Client Error: Too Many
Requests for ur: https://www.google.com/sorry/index?
continue=https://www.youtube.com/
watch%3Fv%3D[VIDEO_ID]&q=EgQ2u8j_GLbL-
KAGIjAukVmdqg8119WeKzDXMfrwHXiNez3e3URj-
_IJQGuReRYRc9Gkln40VXAlfSe301kyAXI! This is most likely
caused by:

Request to YouTube failed: [VIDEO_ID]

Any ideas for working around this issue?

Thank you!

**Comment by jdepoix** [comment]
@lovetcodes did this solve your issue? Can this be closed?

**Comment by jdepoix** [comment]
Close due to inactivity
