### ISSUE TITLE
Is there currently a way to return just the list of language_codes from manual and auto generated videos?

### ISSUE THREAD

**Issue by wes-kay** [jdepoix/youtube-transcript-api#201]
Looking through the api I wasn't able to see anything that would handle returning back auto generated as well as manual language_codes, this is the current solution I've come up with:

```
def get_languages(video_id):
    try:
        transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)
        if len(transcript_list._generated_transcripts) == 0:
            values_list = list(transcript_list._manually_created_transcripts.values())
        else:
            values_list = list(transcript_list._generated_transcripts.values())
        
        return [item.language_code for item in values_list]

    except Exception as e:
        return None
```

Please let me know if there's a better way.

**Comment by jdepoix** [comment]
Hi @wes-kay, the `TranscriptList` class is iterable. So you can simply do `[transcript.language_code for transcript in YouTubeTranscriptApi.list_transcripts(video_id)]` to iterate over all transcripts.
