### ISSUE TITLE
Mismatch in Start Time and Duration

### ISSUE THREAD

**Issue by prateekjoshi565** [jdepoix/youtube-transcript-api#21]
Hi,

I extracted the subtitles of a video (video id - Li9R5RI5kdQ). For some of the phrases Start time + duration is greater than the start time of the next phrases.

Is that a bug or I am missing something?

Thanks in advance!

**Comment by jdepoix** [comment]
Hi,

`start` is the point in time when the subtitle box appears on screen in the youtube video and `duration` is how long it is displayed. As there often is some overlap between subtitle boxes, this can happen.

**Comment by i3abghany** [comment]
I've tried this on several auto-generated captions and it always fails as `start` + `duration` exceeds the starting time of the next subtitle.

**Comment by jdepoix** [comment]
@i3abghany please read my previous answer. It explains why this is the case.

**Comment by phoebe-lin** [comment]
Can I ask a dump question. Are start and duration in the same unit (i.e., second)?

**Comment by phoebe-lin** [comment]
@jdepoix Can I ask a dump question. Are start and duration in the same unit (i.e., second)?

**Comment by jdepoix** [comment]
@phoebe-lin yes, both are in seconds

**Comment by croquies** [comment]
I found out that usually the duration is like this.
The 0th text's duration is 2nd (not 1st) text's start - 0th text's start.
duration[0] = start[2] - start[0].

**Comment by piyushgit011** [comment]
you can use this code to get the end timings , thanks 
code :-

from youtube_transcript_api import YouTubeTranscriptApi

# Specify the YouTube video ID
video_id = 'your_video_id_here'

# Fetch the transcript
transcript = YouTubeTranscriptApi.get_transcript(video_id)

# Calculate end time and adjust duration
for i in range(len(transcript)):
    start = transcript[i]['start']
    if i < len(transcript) - 1:
        next_start = transcript[i + 1]['start']
        end = next_start
        duration = next_start - start
    else:
        duration = transcript[i]['duration']
        end = start + duration
    text = transcript[i]['text']
    print(f"Start: {start:.2f}s, End: {end:.2f}s, Duration: {duration:.2f}s, Text: {text}")

**Comment by dai-shuo** [comment]
> I found out that usually the duration is like this. The 0th text's duration is 2nd (not next, but next next item) text's start - 0th text's start. duration[0] = start[2] - start[0].

the texts are the rolling subtitle lines you see while watching a video. 
typically, there are 2 visible subtitle lines on the screen at any given time, that’s why the 0th line remains visible until the 2nd line appears.
