### ISSUE TITLE
[ERROR] Too Many Requests For URL, Request to YouTube failed

### ISSUE THREAD

**Issue by saousername** [jdepoix/youtube-transcript-api#223]
DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# Error
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.youtube.com/watch%3Fv%3DhKvzg7VMbv0&q=EgQ2v_0MGKKJt6cGIjAXWwEp36DAO5Bjq5b4pqsJdyQmg-9-4PAfT4BV7ogFjyoJ4IkqjZTX5xHwso4U6XUyAXJaAUM! This is most likely caused by:

Request to YouTube failed: hKvzg7VMbv0

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues.

### Which Python version are you using?
Python 3.9.1

### Which version of youtube-transcript-api are you using?
most recent

# Expected behavior
I expected to receive a transcript for video ID hKvzg7VMbv0

# Actual behaviour
Instead I got the above error message.

Is this something to do with proxy IPs/YouTube rate limits? If so, how do I get around the issue?

**Comment by JerryZhou54** [comment]
Getting same error as well

**Comment by saousername** [comment]
Looks like it's working now
