### ISSUE TITLE
error: Subtitles are disabled for this video even when subtitles are available on video

### ISSUE THREAD

**Issue by JohnVersus** [jdepoix/youtube-transcript-api#228]
# To Reproduce
Steps to reproduce the behavior: Try to get the subtitle for: https://www.youtube.com/watch?v=KXF6NRtBHec

### What code / cli command are you executing?
I am using the below function to get the subs
```
`transcript_list.find_manually_created_transcript` and `transcript_list.find_generated_transcript`
```

### Which Python version are you using?
Python 3.10.6

### Which version of youtube-transcript-api are you using?
Tested with the latest version

# Expected behavior

I expected to receive the russian transcript but received

# Actual behaviour
Describe what is happening instead of the **Expected behavior**. Add **error messages** if there are any. 

Received this error
```
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=KXF6NRtBHec! This is most likely caused by:

Subtitles are disabled for this video
```

**Comment by jdepoix** [comment]
Hi @JohnVersus, you can't retrieve this transcript as the video is age-restricted (you'll actually see that if you open it in an incognito tab in your browser). Unfortunately, there currently is no proper error message for this (see #111). However, you can still retrieve transcripts for age-restricted videos using [cookies](https://github.com/jdepoix/youtube-transcript-api/#cookies).
