### ISSUE TITLE
subtitles file saving

### ISSUE THREAD

**Issue by i3abghany** [jdepoix/youtube-transcript-api#23]
I think it would be great if we had a feature that saves the subtitle as a `.srt`, `.vtt` or another subtitles format, I'd also like to say that I think that I can implement this feature, I already did some work and I think I can get it to work, should I pull and proceed to do it? As I don't see anything about contributing in the documentation, so I thought I'd ask in a separate issue.

**Comment by jdepoix** [comment]
Hi @i3abghany,

that could be a great feature!

I haven't come around to add a contribution guideline, as there only has been one contribution so far. But absolutely feel free to submit your contribution!

However, I am not a fan of doing the file handling in the `YouTubeTranscriptApi`, as I feel this would not integrate that nicely into the CLI and limit the flexibility of this feature. I would suggest just adding a format param to the `get_transcript` and `get_transcripts` functions (with the default being `YouTubeTranscriptApi.Format.JSON`):
```python
YouTubeTranscriptApi.get_transcript(video_id, format=YouTubeTranscriptApi.Format.SRT)
# and
YouTubeTranscriptApi.get_transcripts(video_ids, format=YouTubeTranscriptApi.Format.SRT)
```
the part of saving it to a file can be done by the client of this API, only if needed. This way it can also be used if the data will be processed further and saving it to a file is not needed.
This would also integrate nicely into the CLI, if it was used like this:
```
youtube_transcript_api <first_video_id> --format svt
# when saving to file
youtube_transcript_api <first_video_id> --format svt > transcript.svt
```
Note, that you'll have to remove the `--json` param and make its functionality part of the `--format` param.

Other than that there are no rules defined for contributions, yet. Just make sure to keep the test coverage at 100% (will be tested by coveralls as part of the travis build pipeline, once you open your PR) and keep the coding style somewhat similar to what it is right now.

Looking forward to your contribution! 😃👍

**Comment by jdepoix** [comment]
Hi @i3abghany,
are you actively working on this? Otherwise I would like to close this issue, as I personally don't have a demand for this feature.

**Comment by jdepoix** [comment]
Due to the lack of a reply I will close this now. Let me know if you'll revisit this and decide to implement it.

**Comment by aliveupstairs** [comment]
I want this feature (in the CLI), @jdepoix. :+1:

**Comment by jdepoix** [comment]
@aliveupstairs as mentioned previously I personally don't have a demand for this feature, but feel free to contribute if that's something you'd like to see in this module.

**Comment by aliveupstairs** [comment]
I'm not a python developer, sadly. With due respect, I don't see the point of a subtitles CLI that doesn't output a usable subtitle file. I appreciate the unixy output, but the CLI shouldn't require a converter script to just use.

**Comment by jdepoix** [comment]
@aliveupstairs regarding the point of this module: I implemented this because I needed it for a data science project and to my knowledge most of the users use it in some sort of data science setting. In this sort of setting a format like srt or vtt is not desirable at all. So I would respectfully disagree with your statement.
But as I stated before, I don't mind this being part of this module, as long it does not intervene with the core functionality, if somebody wants to invest their time into implement it. However, I don't have the time to do so myself at the moment and I don't see the need to do so either, as I would consider this a nice-to-have feature rather than an integral part of the functionality this module is supposed to provide.

**Comment by aliveupstairs** [comment]
I see where you're coming from, @jdepoix. Could you consider opening this issue then? and maybe add a [`help wanted`](https://github.blog/2020-02-12-supercharge-your-command-line-experience-github-cli-is-now-in-beta/#filter-lists-to-your-needs) label?

**Comment by jdepoix** [comment]
@aliveupstairs will do that 👍

**Comment by apoorv-jain** [comment]
Hi! I am not very adept in coding in open source but definitely want to help you . Just required help from you. I will do all the file handling for you and can create it into .srt files. Just required your help in integrating it in CLI as I am not adept with command line arguments.
Please if you could only guide me a little it would help you and me as well.

**Comment by jdepoix** [comment]
@apoorv-jain Glad to hear that, but could you provide some more information on what kind of help you need exactly? The `argparse` module is fairly well documented (https://docs.python.org/3/library/argparse.html) and I already outlined how the API for this could looks like in the comment above (https://github.com/jdepoix/youtube-transcript-api/issues/23#issuecomment-532592368). Also I would prefer the file handling to not be part of this module as explained in that comment.

**Comment by apoorv-jain** [comment]
Okay I had been working on this srt format and what all the formats do you want to be included.
Thanks for providing the library for the parsing the CLI commands .
This would be my first open source contribution thus please feel free to correct me at any point of time.
The help I needed is where does the code for parsing out the file is situated. I just wanted to ask that. Rest I will try my best to implement this feature.

**Comment by jdepoix** [comment]
@apoorv-jain I suggest adding a `_formatting` module which contains the classes `SrtFormatter`, `VttFormatter` and so on which all implement the following interface:
```python
class TranscriptFormatter():
    def format(self, transcript_data):
        pass
```
A user of this module could then use it like this:
```python
SrtFormatter().format(
    YouTubeTranscriptApi.list_transcripts(video_id).find_transcript(language).fetch()
)
```

**Comment by apoorv-jain** [comment]
Okay I will try and work  on it and how do you want it in the CLI format.

**Comment by jdepoix** [comment]
As stated above

**Comment by apoorv-jain** [comment]
@jdepoix  One More thing I encountered is that do I have to export all the files if a person asks for multiple languages as `_en` `_de` as the extra name added??

**Comment by jdepoix** [comment]
@apoorv-jain this is one of the many reasons why I don't want the file handling to be done by this module. Just return the data in the correct format and then the user can do with it whatever he wants!

**Comment by apoorv-jain** [comment]
But it might not be as difficult to implement in API but a little bit in the CLI.
I will keep both the versions at hand you could choose which will be better

**Comment by jdepoix** [comment]
It's not about the file handling being difficult to implement, it's more a matter of keeping the separation of concerns. File handling can easily be done by the user and he can do it to his liking. If it is implemented in the CLI doing something like `youtube_transcript_api <first_video_id> --format svt > transcript.svt` allows you to save the transcript to a file, without much effort.

**Comment by apoorv-jain** [comment]
Ohkay I'll try to implement it. But please be patient as I am novice on these kinds of things but will try my best.

**Comment by jdepoix** [comment]
Support for WebVVT has been added in `v0.4.0`. Thanks to @crhowell! 🥳

**Comment by crhowell** [comment]
It is a very simple implementation to WebVTT. WebVTT has a bit more depth to its specification, but it is a starting point if anyone wants to add to it in the future. 😄
