### ISSUE TITLE
Socks5 proxy support

### ISSUE THREAD

**Issue by leohuang2013** [jdepoix/youtube-transcript-api#231]
**Is your feature request related to a problem? Please describe.**
Is possible to support sock5 as proxy?

Currently, youtube-transcript-api supports https as proxy, I think socks5 would be help as some project only allow socks5, like us.

**Comment by jdepoix** [comment]
Hi @leohuang2013, sorry for the late reply!

The `proxies` param is just passed through to requests. I haven't tried this myself, but according to [stackoverflow](https://stackoverflow.com/a/69200472), you only need to install `requests[socks]` to be able to use sock5 urls as part of the requests proxy config. So you should be able to do run this:
```python
YouTubeTranscriptApi.get_transcript(video_id, proxies={
    'http': 'socks5://user:pass@host:port',
    'https': 'socks5://user:pass@host:port',
})
```
