### ISSUE TITLE
Transcriptsdisabled

### ISSUE THREAD

**Issue by Pavankumar44** [jdepoix/youtube-transcript-api#232]
DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# To Reproduce

### What code / cli command are you executing?
Im running the code in colaboratory
and getting the error
Subtitles are disabled for this video

```
YouTubeTranscriptApi.get_transcript ...
```

### Which Python version are you using?
Python 3.21

### Which version of youtube-transcript-api are you using?
youtube-transcript-api x.y.z

# Expected behavior
Describe what you expected to happen. 
It needs to extract the transcript from the video

For example: I expected to receive the english transcript

# Actual behaviour
Describe what is happening instead of the **Expected behavior**. Add **error messages** if there are any. 

For example: Instead I received the following error message:
```
# ... error message ...
```
TranscriptsDisabled                       Traceback (most recent call last)
[<ipython-input-18-aa398df839f5>](https://localhost:8080/#) in <cell line: 1>()
----> 1 YouTubeTranscriptApi.get_transcript(video_id)
      2 transcript = YouTubeTranscriptApi.get_transcript(video_id)

3 frames
[/usr/local/lib/python3.10/dist-packages/youtube_transcript_api/_transcripts.py](https://localhost:8080/#) in _extract_captions_json(self, html, video_id)
     60                 raise VideoUnavailable(video_id)
     61 
---> 62             raise TranscriptsDisabled(video_id)
     63 
     64         captions_json = json.loads(

TranscriptsDisabled: 
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=u7TC5RBd1rK0M0gy! This is most likely caused by:

Subtitles are disabled for this video

**Comment by cgreening** [comment]
Just hit this as well - but there is a transcript and auto generated subtitles are there.

**Comment by jdepoix** [comment]
Hi @Pavankumar44, it looks like you are trying to retrieve the transcript for a video with the ID `u7TC5RBd1rK0M0gy`. However, there is no such video: https://www.youtube.com/watch?v=u7TC5RBd1rK0M0gy
