### ISSUE TITLE
429 Client Error: Too Many Requests

### ISSUE THREAD

**Issue by world-DESIGNER** [jdepoix/youtube-transcript-api#233]
### What code / cli command are you executing?
I am running the following code to fetch a YouTube video transcript:

`YouTubeTranscriptApi.get_transcript(video_id, languages=['en'])`

### Which Python version are you using?
Python 3.8.

### Which version of youtube-transcript-api are you using?
0.4.1

# Expected behavior
I expected to receive the English transcript of the provided YouTube video ID without any errors.

# Actual behaviour
Instead of getting the transcript, I received a `429 Client Error: Too Many Requests` response from the YouTube server, which indicates that my application has sent too many requests in a given amount of time and thus has been rate-limited. But I'm getting this error over the last two days

**Comment by jdepoix** [comment]
Hi @world-DESIGNER ,
have a look at this discussion #176, to find out more about rate limits.

Closed as this is a duplicate.
