### ISSUE TITLE
'charmap' codec can't encode character '\u0101'

### ISSUE THREAD

**Issue by BillionShields** [jdepoix/youtube-transcript-api#235]
DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# To Reproduce
run CLI with list of YT clips 
### What code / cli command are you executing?
For example: I am running
```
youtube_transcript_api "BwyZIWeBpRw" --format text  >>"temp.txt"
youtube_transcript_api "at37Y8rKDlA" --format text  >>"temp.txt"
```
all those
17O5mgXZ9ZU
4b6bwcWK6GE
6ZrlsVx85ek
at37Y8rKDlA
BwyZIWeBpRw
ErrorCOde
FFwA0QFmpQ4
gMRph_BvHB4
H-XfCl-HpRM
hcuMLQVAgEg
hx3U64IXFOY
J7SrAEacyf8
JPX8g8ibKFc
LG53Vxum0as
LVxL_p_kToc
mcPSRWUYCv0
NAATB55oxeQ
qJXKhu5UZwk
ufsIA5NARIo
uuP-1ioh4LY
vA50EK70whE
x7qbJeRxWGw
XfURDjegrAw

### Which Python version are you using?
Python 3.12

### Which version of youtube-transcript-api are you using?
youtube-transcript-api 2023.7.22

# Expected behavior
Describe what you expected to happen. 

For example: I expected to receive the english transcript

# Actual behaviour
Describe what is happening instead of the **Expected behavior**. Add **error messages** if there are any. 

empty file and error 
```
ine 88, in _run_code
  File "\Python312\Scripts\youtube_transcript_api.exe\__main__.py", line 7, in <module>
  File "\Python312\Lib\site-packages\youtube_transcript_api\__main__.py", line 11, in main
    print(YouTubeTranscriptCli(sys.argv[1:]).run())
  File "\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u0101' in position 1891: character maps to <undefined>
        1 file(s) moved.

**Comment by jdepoix** [comment]
Hi @BillionShields,
I tried a few of the IDs in your list. It seems that none of them have a transcript available in `en` (some of them in `en-US` however). I would assume that your error is linked to the error message returned by `youtube-trancript-api` in those cases.

**Comment by jdepoix** [comment]
Closed due to inactivity
