### ISSUE TITLE
Adding an example with output

### ISSUE THREAD

**Issue by pauljnorg** [jdepoix/youtube-transcript-api#237]
I'm learning some standards, please accept my apologies for veering off the standard
My intention for this issue is just to add an example with output, breaking down the output into paragraphs and sentences of 5-line paragraphs and 15-word lines. The paragraphs and sentences are pseudo as the script isn't looking for logical sentences. 

I've forked the repository and have 2 examples written, run.py and fixthisrun.py
These Python scripts pull the transcript from the video on YouTube, and further updates to the examples will accept the videoID(s) as args.

As I'm fairly new to the standards in Github, any feedback on my interaction is welcome and appreciated.   

Thank You, Paul

**Comment by jdepoix** [comment]
Hi @pauljnorg, the discussions around a PR should usually be held within the "Conversation" section of that PR. The "Issues" section is more to report bugs or request features.

**Comment by pauljnorg** [comment]
Thank You for that, 

I was looking for something like that, but I haven't learned enough.
