### ISSUE TITLE
SSL Errors when using transcript API

### ISSUE THREAD

**Issue by vahndi** [jdepoix/youtube-transcript-api#239]
DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# To Reproduce

### What code / cli command are you executing?
I am running
```
from youtube_transcript_api import YouTubeTranscriptApi
transcript_list = YouTubeTranscriptApi.list_transcripts('pxiP-HJLCx0')
```

### Which Python version are you using?
Python 3.9

### Which version of youtube-transcript-api are you using?
youtube-transcript-api 0.6.1

# Expected behavior
Get list of transcripts for video

# Actual behaviour
Instead I received the following error message:
```
SSLError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /watch?v=pxiP-HJLCx0 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))
```

**Comment by benrapport** [comment]
I am seeing this as well!

**Comment by sumersao** [comment]
Also having this issue!

**Comment by lober-io** [comment]
With Python 3.10.11 and youtube-transcript-api  0.6.1 its working for me

**Comment by vahndi** [comment]
I realized this is an OpenSSL issue in Windows. This was causing requests (and pip) to fail.
