### ISSUE TITLE
Get auto-generated subtitles even when both the (manually created) and (auto-generated) subtitles exists.

### ISSUE THREAD

**Issue by SenpaiKishore** [jdepoix/youtube-transcript-api#248]
I want to select the (GENERATED) subtitle instead of (MANUALLY CREATED) when I run the following line in python: 
```python
YouTubeTranscriptApi.get_transcript(video_id, languages=["en"])
```

`YouTubeTranscriptApi.list_transcripts(video_id)` returns this list of subtitles:
```bash
For this video (N2bXEUSAiTI&list=PLBjE6akKYpgiFB-X-WL4oOU4GyVZGYwio) transcripts are available in the following languages:

(MANUALLY CREATED)
 - en ("English - Twitch Chat")[TRANSLATABLE]

(GENERATED)
 - en ("English (auto-generated)")[TRANSLATABLE]
```

I am trying to get the subtitles of this video(ID): `N2bXEUSAiTI&list=PLBjE6akKYpgiFB-X-WL4oOU4GyVZGYwio`

**Comment by jdepoix** [comment]
Hi @SenpaiKishore, please read the [docs](https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#list-available-transcripts)
