### ISSUE TITLE
Getting transcript in the original language

### ISSUE THREAD

**Issue by mgoldenbe** [jdepoix/youtube-transcript-api#252]
What is the most straightforward way to get transcript in the language spoken in the video? Is it to first get the list of auto-generated transcripts? If so:

- Can I be certain that the list of auto-generated transcripts will contain exactly one element?
- What can I do when the author removed auto-generated transcript, such as for this video: [https://youtu.be/rfscVS0vtbw](https://youtu.be/rfscVS0vtbw)

**Comment by GorujoCY** [comment]
This kind of post belongs to **Discussion** than an issue...
this is a question not an issue.

**Comment by mgoldenbe** [comment]
I only see the button New Issue. How do I open a discussion?

**Comment by jdepoix** [comment]
Hi @mgoldenbe,
There's three questions here I think:

> What is the most straightforward way to get transcript in the language spoken in the video?

There is none unfortunately. Currently english is always used as the default language. There is an issue open for changing the default behaviour to return the default transcript of the video (#133), but it hasn't been implemented yet. However, even this wouldn't guarantee that the transcript you get is the language spoken in the video.

> Can I be certain that the list of auto-generated transcripts will contain exactly one element?

To be honest, I don't know. This module just pulls information from YouTube and it's hard to give guarantees about anything YouTube is doing. My guess would be that there's some cases where there could be multiple, but there's only one in most. So in those cases where there's only one, you could use that as a hint towards which language is the language spoken in the video. But my experience in working on this module has been that there's basically an exception for everything, so there will most certainly be some weird cases,where this logic doesn't work out. Feel free to share your findings if you play around with this!

> What can I do when the author removed auto-generated transcript, such as for this video

Nothing you can do here I think.
