### ISSUE TITLE
issue while extracting text from youtube video using youtube_transcript_api

### ISSUE THREAD

**Issue by Midhun134** [jdepoix/youtube-transcript-api#257]
![Screenshot 2024-02-23 162545](https://github.com/jdepoix/youtube-transcript-api/assets/150249946/22c6aaae-77c4-414f-b2ba-2ebbf689be7a)

I am using python version  3.11.8

**Comment by PetrKubes97** [comment]
Hi, I think the issue might be that the video id is not "rJu-..." but "RgKAFK...". There seem to be some changes in the youtube url structure.
