### ISSUE TITLE
Error downloading the transcript 

### ISSUE THREAD

**Issue by nicholasguimaraes** [jdepoix/youtube-transcript-api#26]
I'm getting an error saying that the video or the subtitles might be no longer available but this isn't true.

I'm simply passing a .txt file with the video ids I want to have the transcript.

Here's the error I'm getting,

C:\youtube_transcripts_mp3>python get_transcript.py id.txt
Traceback (most recent call last):
  File "C:\youtube_transcripts_mp3\youtube_downloads\lib\site-packages\youtube_transcript_api\_api.py", line 93, in get_transcript
    return _TranscriptParser(_TranscriptFetcher(video_id, languages, proxies).fetch()).parse()
  File "C:\youtube_transcripts_mp3\youtube_downloads\lib\site-packages\youtube_transcript_api\_api.py", line 153, in parse
    for xml_element in ElementTree.fromstring(self.plain_data)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\xml\etree\ElementTree.py", line 1314, in XML
    parser.feed(text)
TypeError: a bytes-like object is required, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_transcript.py", line 15, in <module>
    Transcript = YouTubeTranscriptApi.get_transcript(video_id, languages=['pt'])
  File "C:\youtube_transcripts_mp3\youtube_downloads\lib\site-packages\youtube_transcript_api\_api.py", line 95, in get_transcript
    raise YouTubeTranscriptApi.CouldNotRetrieveTranscript(video_id)
youtube_transcript_api._api.CouldNotRetrieveTranscript: Could not get the transcript for the video https://www.youtube.com/watch?v=MzRoOMF8XEQ
! This usually happens if one of the following things is the case:
 - subtitles have been disabled by the uploader
 - none of the language codes you provided are valid
 - none of the languages you provided are supported by the video
 - the video is no longer available.

Here are the video IDs,

MzRoOMF8XEQ
J3Yo1Tz1YXg

You can check yourself that both videos are still on youtube and they have auto generated subtitles available.

What should I do?

**Comment by jdepoix** [comment]
Apparently Google just changed something about how the their Transcript API works, therefore this module is currently not working at all. I am looking in to this and try to fix it asap!

**Comment by jdepoix** [comment]
Just fixed this with v0.1.8. It is now available on PyPi. Sorry for the inconveniences!

**Comment by nicholasguimaraes** [comment]
That was fast! Thank you very much
