### ISSUE TITLE
Cant get the transcripts anymore

### ISSUE THREAD

**Issue by JesseKanter** [jdepoix/youtube-transcript-api#27]
Having trouble getting transcripts, it was working fine yesterday.

I get the following error:

TypeError                                 Traceback (most recent call last)
/anaconda3/envs/insight/lib/python3.7/site-packages/youtube_transcript_api/_api.py in get_transcript(cls, video_id, languages, proxies)
     92         try:
---> 93             return _TranscriptParser(_TranscriptFetcher(video_id, languages, proxies).fetch()).parse()
     94         except Exception:

/anaconda3/envs/insight/lib/python3.7/site-packages/youtube_transcript_api/_api.py in parse(self)
    152             }
--> 153             for xml_element in ElementTree.fromstring(self.plain_data)
    154             if xml_element.text is not None

/anaconda3/envs/insight/lib/python3.7/xml/etree/ElementTree.py in XML(text, parser)
   1314         parser = XMLParser(target=TreeBuilder())
-> 1315     parser.feed(text)
   1316     return parser.close()

TypeError: a bytes-like object is required, not 'NoneType'

During handling of the above exception, another exception occurred:

CouldNotRetrieveTranscript                Traceback (most recent call last)
<ipython-input-98-40deeb0d20fe> in <module>
----> 1 comments('VjizMuzCltY')

<ipython-input-93-81db1547bd25> in comments(video_id)
    247 def comments(video_id):   #request
    248     #video_id=request.GET['video_id']
--> 249     tran= get_transcript_df(video_id)
    250     comments= get_comments_df(video_id)
    251 

<ipython-input-93-81db1547bd25> in get_transcript_df(video_id_input)
    148     duration=[]
    149 
--> 150     for dic in YouTubeTranscriptApi.get_transcript(video_id_input):
    151         text+=[dic['text']]
    152         start+=[dic['start']]

/anaconda3/envs/insight/lib/python3.7/site-packages/youtube_transcript_api/_api.py in get_transcript(cls, video_id, languages, proxies)
     93             return _TranscriptParser(_TranscriptFetcher(video_id, languages, proxies).fetch()).parse()
     94         except Exception:
---> 95             raise YouTubeTranscriptApi.CouldNotRetrieveTranscript(video_id)
     96 
     97 

CouldNotRetrieveTranscript: Could not get the transcript for the video https://www.youtube.com/watch?v=VjizMuzCltY! This usually happens if one of the following things is the case:
 - subtitles have been disabled by the uploader
 - none of the language codes you provided are valid
 - none of the languages you provided are supported by the video
 - the video is no longer available.

If none of these things is the case, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues

**Comment by JesseKanter** [comment]
I have been relying pretty heavy on this so please let me know soon if you have any suggestions. Thanks!

**Comment by jdepoix** [comment]
Apparently Google just changed something about how the their Transcript API works, therefore this module is currently not working at all. I am sorry if this gets you into trouble, but you have been warned that this can happen at any time due to the nature of this module (https://github.com/jdepoix/youtube-transcript-api#warning).

I will do my best to fix this as soon as possible, but I can not give you an ETA as I don't know yet, what has to be changed to make it work again. Also I can't promise that it will be fixable at all.

**Comment by JesseKanter** [comment]
I understand. Thank you for responding. Please let me know if you do resolve it. Thank you again, I really appreciate it.

**Comment by jdepoix** [comment]
Just fixed this with v0.1.8. It is now available on PyPi. Sorry for the inconveniences!
