### ISSUE TITLE
Bug in _transcripts.py line 37 raise YouTubeRequestFailed(error, video_id)

### ISSUE THREAD

**Issue by tbelfort** [jdepoix/youtube-transcript-api#270]
I deleted, because it's not relevant. I just spotted this while reading the code. :-)

The code in _errors.py is

class YouTubeRequestFailed(CouldNotRetrieveTranscript):
CAUSE_MESSAGE = 'Request to YouTube failed: {reason}'

def __init__(self, video_id, http_error):
    self.reason = str(http_error)
    super(YouTubeRequestFailed, self).__init__(video_id)

Ie, video_id, http_error, but it's called with YouTubeRequestsFailed(error, video_id)

**Comment by jdepoix** [comment]
Hi @tbelfort,
Could you please elaborate what you think the issue is here, I don't think I completely understand 🤔 
`super(YouTubeRequestFailed, self).__init__(video_id)` is a call to the parent constructor of `CouldNotRetrieveTranscript`, which seems fine to me?

**Comment by jdepoix** [comment]
closed due to inactivity
