### ISSUE TITLE
[Question]  Authentication, basic questions

### ISSUE THREAD

**Issue by stormsson** [jdepoix/youtube-transcript-api#273]
This could be trivial, please have patience,  but I'm missing a point in how this works:
- where is the transcription from ? audio to text? youtube data ?
- don't i have to use a YT API key to fetch from YT ?

thank you

**Comment by jdepoix** [comment]
This module simply uses the same endpoints which are used by the YouTube web client. Since you are also able to enable subtitles on a YouTube video without being logged in, we are also able to retrieve those without any form of Authentication.
