### ISSUE TITLE
Why are the subtitles obtained incomplete?

### ISSUE THREAD

**Issue by 2322312693** [jdepoix/youtube-transcript-api#274]
The content of the first sentence is not finished
will appear in the second subtitle

：
{
"duration": 6.56,
"start": 0.16,
"text": "what are you going to do with us now I'm  taking you to your parents can't we just  "
},
{
"duration": 8.28,
"start": 6.72,
"text": "forget the whole thing no then I'll get in  trouble with my boss please we'll also get  "
},

**Comment by 2322312693** [comment]
please help me

**Comment by jdepoix** [comment]
The transcripts are grouped into snippets as they are displayed in YouTube. Each snippet corresponds to one subtitles line in the web player. Therefore, it's to be expected that they usually don't correspond to a full sentence.

I will close this now, as there is nothing we can do here.
