### ISSUE TITLE
Too Many Requests for url

### ISSUE THREAD

**Issue by zjrwtx** [jdepoix/youtube-transcript-api#280]
![image](https://github.com/jdepoix/youtube-transcript-api/assets/86822589/02755991-13c7-4c9c-8a3c-2300949ecbbb)

DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# To Reproduce

### What code / cli command are you executing?
For example: I am running
```
YouTubeTranscriptApi.get_transcript ...
```

### Which Python version are you using?
Python x.y

### Which version of youtube-transcript-api are you using?
youtube-transcript-api x.y.z

# Expected behavior
Describe what you expected to happen. 

For example: I expected to receive the english transcript

# Actual behaviour
Describe what is happening instead of the **Expected behavior**. Add **error messages** if there are any. 

For example: Instead I received the following error message:
```
# ... error message ...
```

**Comment by jdepoix** [comment]
Hi @zjrwtx, are you able to make request to YouTube in general from that machine? According to your GitHub profile, you are from China and AFAIK YouTube is blocked there. If you can't access YouTuber, this module won't work.

**Comment by zjrwtx** [comment]
thanks for your quick reply，actually，i use the proxy,which let me access the youtuber fluently,and i have tested before,it worked,but todys test is unwork







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jonas ***@***.***&gt;; 
发送时间: 2024年4月25日(星期四) 下午4:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jdepoix/youtube-transcript-api] Too Many Requests for url (Issue #280)














 
Hi @zjrwtx, are you able to make request to YouTube in general from that machine? According to your GitHub profile, you are from China and AFAIK YouTube is blocked there. If you can't access YouTuber, this module won't work.

**Comment by zjrwtx** [comment]
thanks you guys，now it works！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jonas ***@***.***&gt;; 
发送时间: 2024年4月25日(星期四) 晚上6:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jdepoix/youtube-transcript-api] Too Many Requests for url (Issue #280)














 
So the module has worked for you before and only today it does not? Does it not work for any IDs, or only for this specific one? And are you still able to access YouTube in general today?
