### ISSUE TITLE
works for some videos and not others

### ISSUE THREAD

**Issue by JesseKanter** [jdepoix/youtube-transcript-api#29]
Hi, I had written previously when this wasnt working earlier this week and the author updated and that worked great. Thank you!

It does now seem that I am getting the same error as last time but only for certain videos. Most watch mojo videos on youtube I cannot get transcripts for, most John oliver last week tonight upsides I can.

Any idea why some might not be accessible? I can see their transcripts on the actual website.

Thanks.

Below is the error I get:
ParseError                                Traceback (most recent call last)
/anaconda3/envs/insight/lib/python3.7/site-packages/youtube_transcript_api/_api.py in get_transcript(cls, video_id, languages, proxies)
     92         try:
---> 93             return _TranscriptParser(_TranscriptFetcher(video_id, languages, proxies).fetch()).parse()
     94         except Exception:

/anaconda3/envs/insight/lib/python3.7/site-packages/youtube_transcript_api/_api.py in parse(self)
    159             }
--> 160             for xml_element in ElementTree.fromstring(self.plain_data)
    161             if xml_element.text is not None

/anaconda3/envs/insight/lib/python3.7/xml/etree/ElementTree.py in XML(text, parser)
   1314         parser = XMLParser(target=TreeBuilder())
-> 1315     parser.feed(text)
   1316     return parser.close()

ParseError: not well-formed (invalid token): line 2, column 972

During handling of the above exception, another exception occurred:

CouldNotRetrieveTranscript                Traceback (most recent call last)
<ipython-input-46-036577b9700d> in <module>
----> 1 Confed_transcript=YouTubeTranscriptApi.get_transcript('-VidQFzpW7M')

/anaconda3/envs/insight/lib/python3.7/site-packages/youtube_transcript_api/_api.py in get_transcript(cls, video_id, languages, proxies)
     93             return _TranscriptParser(_TranscriptFetcher(video_id, languages, proxies).fetch()).parse()
     94         except Exception:
---> 95             raise YouTubeTranscriptApi.CouldNotRetrieveTranscript(video_id)
     96 
     97 

CouldNotRetrieveTranscript: Could not get the transcript for the video https://www.youtube.com/watch?v=-VidQFzpW7M! This usually happens if one of the following things is the case:
 - subtitles have been disabled by the uploader
 - none of the language codes you provided are valid
 - none of the languages you provided are supported by the video
 - the video is no longer available.

If none of these things is the case, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues

**Comment by jdepoix** [comment]
Fixed with v0.1.9
