### ISSUE TITLE
How about YouTube Shorts?

### ISSUE THREAD

**Issue by brycewang2018** [jdepoix/youtube-transcript-api#292]
When I tried to download the transcripts from a YouTube short video, I met this bug:

"""
TranscriptsDisabled: 
Could not retrieve a transcript for the video **https://www.youtube.com/watch?v=IsAwf3qrSw0S2MhN!** This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
"""

I think it might be not hard to add some new codes to support the short video URL. 

Thanks!

**Comment by jdepoix** [comment]
Hi @brycewang2018,
shorts work for me. However, when I open the link you posted it says that the "video is no longer available", which most likely is the cause for this error.

**Comment by brycewang2018** [comment]
You are right. Thank you for your response.
