### ISSUE TITLE
Cannot retrieve transcript from any video with subtles since June 7th

### ISSUE THREAD

**Issue by gnx555** [jdepoix/youtube-transcript-api#293]
DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# To Reproduce

### What code / cli command are you executing?
youtube_transcript_api iPcWRWH9mio

### Which Python version are you using?
Python 3.9.8

### Which version of youtube-transcript-api are you using?
youtube-transcript-api 0.6.2

# Expected behavior
I expected to receive the english transcript

# Actual behaviour
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=iPcWRWH9mio! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!

# Question
Is YouTube blocking my server to retrieve transcript?

**Comment by Aubinga** [comment]
Facing the same issue.

**Comment by jonespm** [comment]
This video is currently working fine for me on 2024-06-15

```
➜  ~ youtube_transcript_api "iPcWRWH9mio"
[[{'duration': 6.08,
   'start': 0.799,
   'text': "hi I'm lazy and I bet you are too no"},
```

I wonder if this is related to all the news in the last week about Youtube testing their new server-side ads with some users/regions? That feels like it's mostly a way to block LLM's and retrieval like this, as well as browser extensions. 

* [YouTube Is Experimenting With a Way to Kill Ad Blockers for Good
](https://lifehacker.com/tech/youtube-experimenting-with-a-way-to-kill-ad-blockers-for-good)
* [YouTube tests server-side ads to make your coveted blocker obsolete
](https://www.androidcentral.com/apps-software/youtube-server-side-injectable-ads-test)

**Comment by acordier16** [comment]
Same issue here. Probably IP-banning from Google / YT. Having the issue on a Vultr server (Paris-located), but not from my home IP (Paris-located).
