### ISSUE TITLE
Unable to retrieve transcript for YouTube video using youtube_transcript_api

### ISSUE THREAD

**Issue by Alefiya21** [jdepoix/youtube-transcript-api#294]
I'm experiencing an issue with retrieving the transcript for a YouTube video using the `youtube_transcript_api` library. I've checked the video ID, transcript availability, and API status, but the issue persists.

Version: 0.6.2

**Code:**
```python
from youtube_transcript_api import YouTubeTranscriptApi

video_id = "R0jEmIlydqyrZgX6"
transcript_text = YouTubeTranscriptApi.get_transcript(video_id)

**Comment by jermwatt** [comment]
The video_id you provide is 16 characters long.   

It looks like the [length of a youtube video id is 11, not 16](https://stackoverflow.com/questions/6180138/whats-the-maximum-length-of-a-youtube-video-id).

I get a "no file exists" reply when attempting to visit the youtube video associated with the id you provide 

https://www.youtube.com/watch?v=R0jEmIlydqyrZgX6

Make sure you have the right id.

**Comment by jdepoix** [comment]
You haven't provided the exact error you're getting, but indeed it looks like your video ID is not valid. I'll close this now.
