### ISSUE TITLE
youtube transcripts not working in droplets

### ISSUE THREAD

**Issue by auspy** [jdepoix/youtube-transcript-api#304]
DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# To Reproduce

### What code / cli command are you executing?
For example: I am running
```
YouTubeTranscriptApi.list_transcripts(id)
```

### Which Python version are you using?
Python 3.11

### Which version of youtube-transcript-api are you using?
youtube-transcript-api 0.6.2

# Expected behavior
Youtube transcript should have been fetched

# Actual behaviour
youtube transcripts are not being fetched. it works fine when running on my machine or docker container on my machine but fails for same id in docker container on droplet.
i removed all firewalls and used --network host to use the host network. host i.e, the droplet fails on ping6 but works on ping4 and ping youtue.com.
any help will be much appreciated.

**Comment by jdepoix** [comment]
Hi @auspy, please provide the exact error message and some video IDs for which it is failing and some for which it is not failing.

**Comment by auspy** [comment]
> Hi @auspy, please provide the exact error message and some video IDs for which it is failing and some for which it is not failing.

it failed for every id I tested in droplet. eg: brchILVjj7s,Z1GnEgCcCWE, kb2cEb20KXE

error message is the same. it tells that subtitles does not exist and report an issue if subtitles exist. something like that

I think this is is network issue but for now i don't understand how to solve it.

**Comment by jdepoix** [comment]
Please copy-paste the exact Exception you are getting.

**Comment by auspy** [comment]
> Please copy-paste the exact Exception you are getting.

Subtitles are disabled for this video
If you are sure that the described cause is not responsible for this error

**Comment by auspy** [comment]
> In that case you are experience the same issue described in #303.
> 
> I will close this now as it is a duplicate to that one. You can read through the conversation to get all the relevant information.

thank you for so fast reply
