### ISSUE TITLE
Getting 'Subtitles are disabled for this video' as it is disabled in public YouTube but generates in a logged in account

### ISSUE THREAD

**Issue by daffinia1234** [jdepoix/youtube-transcript-api#306]
Hi,

I'm trying to get the transcript for this video - https://www.youtube.com/watch?v=GMDTx5nTUQs where I do not see the subtitle/caption button enabled if I open it from youtube without logging in but If I login from my account I'm seeing the subtitle getting auto generated (attached the image)  but if I login from another account I'm not seeing it enabled. 
 
is it possible to get the transcript by using any method available in the library?  

thanks

![temp](https://github.com/user-attachments/assets/8b4e47ff-140e-485b-a990-8373de512b07)

**Comment by jdepoix** [comment]
Hi @daffinia1234,
have a look at the [Cookies section in the README](https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#cookies)!

**Comment by daffinia1234** [comment]
just an update, tried with cookies got from this extension - https://chromewebstore.google.com/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc/reviews?hl=en but it did not work! Meanwhile - from my local I can view the page source & get the baseUrl from '"captions":', that url gives the generated transcript. Not sure if any other site information is needed to get video with caption.

**Comment by jdepoix** [comment]
If you can retrieve the transcript locally, but not on a cloud machine, your machines IP might be blocked by YouTube. You can have a look at #303 to find more information on that.

**Comment by daffinia1234** [comment]
sorry when I said locally, I meant in my local browser. The problem what I'm highlighting is, even after passing the cookies via cookies file like `transcript_list = YouTubeTranscriptApi.list_transcripts(video, cookies='new_cookies.txt')`, I'm not getting logged in via library.    

I was checking the content of html after `self._fetch_video_html(video_id)` where it says logged_in false.
`userAgent":"python-requests/2.32.3,gzip(gfe)","clientName":"WEB", "LOGGED_IN":false`

So I'm not sure 1) if my cookies are correct or 2) if youtube is identifying that I'm impersonating as someone and not letting me login or 3) may be, how library http_client uses the cookies is not recognized by youtube.

Need some lead on this- thanks!

**Comment by jdepoix** [comment]
Did you just change the path to the cookies to anonymize it or are you actually using a relative path? If that is the case, maybe try with an absolute path instead, to make sure that this is not the problem.

**Comment by KLM-Nandhu** [comment]
> just an update, tried with cookies got from this extension - https://chromewebstore.google.com/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc/reviews?hl=en but it did not work! Meanwhile - from my local I can view the page source & get the baseUrl from '"captions":', that url gives the generated transcript. Not sure if any other site information is needed to get video with caption.

Hii akka, i have a issues in youtube transcript extraction. but in local youtube_transcript_api is working well. but not in cloud, ena ka pandrathu. neriya try panita roxy u try panita but inu work agala ena pandrathu

**Comment by jdepoix** [comment]
@KLM-Nandhu It sounds like you're referring to issue #303

**Comment by KLM-Nandhu** [comment]
> @KLM-Nandhu It sounds like you're referring to issue #303

how to solve this ?
