### ISSUE TITLE
TranscriptsDisabled only in AWS Cloud, but not on local pc or Google Colab with same proxy

### ISSUE THREAD

**Issue by suhamera** [jdepoix/youtube-transcript-api#313]
# To Reproduce

### What code / cli command are you executing?
I am running
```
from youtube_transcript_api import YouTubeTranscriptApi

video_id = "7gd7HBJJxGQ"
video_transcribtion = YouTubeTranscriptApi.get_transcript(video_id, languages = ['ru'], proxies={"http": "http://A:B@X.X.X.X:59100"})        

for ts in video_transcribtion[:5]:
  print(ts)
```

### Which Python version are you using?
Python 3.12

### Which version of youtube-transcript-api are you using?
youtube-transcript-api 0.6.2

# Expected behavior
I was expecting to get a transcript in Russian. Moreover, I get it on my local computer, in Google Colab. There are no problems at all.

# Actual behaviour
But when I run this code in AWS Lambda, I received the following error message:
```
TranscriptsDisabled: 
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=7gd7HBJJxGQ! This is most likely caused by:

Subtitles are disabled for this video
```

Maybe there are some recommendations on how it can be debugged? I thought that maybe the problem was that the clients are blocked - but the proxy removed that hypothesis.

**Comment by USNA2014** [comment]
Happening to me as well basically.  Works locally, but from my hosting server, says could not retrieve the transcript.

**Comment by cjprist** [comment]
Happening to me as well basically. Works locally, but from my hosting server, says could not retrieve the transcript. Me too

**Comment by USNA2014** [comment]
@cjprist I just got it to work using a proxy.  I set up smartproxy (they had a 3 day free trial).  Got me right through.  So ya, proxy is needed.  Apparently pythonanywhere keeps a static ip for 6 weeks before rotating.  Not sure why locally it works tho.

**Comment by tanmaysingewar** [comment]
It works on the local but not on Servers. In my case, I am using EC2 and it just throws an error: Could not retrieve a transcript for the video 
It might be YouTube is blocking the IPs

**Comment by meyusufdemirci** [comment]
> @cjprist I just got it to work using a proxy. I set up smartproxy (they had a 3 day free trial). Got me right through. So ya, proxy is needed. Apparently pythonanywhere keeps a static ip for 6 weeks before rotating. Not sure why locally it works tho.

How did you able to set up the proxy on the server? I use Heroku.

**Comment by jdepoix** [comment]
Hi @suhamera,
You are only setting up a proxy for http, not for https. This module does https requests, so your proxy won't be used.

I will close this now. There's already a lot of information and discussion on the general issue of IP blocks in #303, so head over there if you want to find out more!
