### ISSUE TITLE
Subtitles are disabled for this video

### ISSUE THREAD

**Issue by ideepankarsharma2003** [jdepoix/youtube-transcript-api#314]
So it is not working for almost every video id I am trying now.

# To Reproduce
```python
YouTubeTranscriptApi.list_transcripts("BAW_RFcFmIU")
```
![image](https://github.com/user-attachments/assets/0b09f68f-0ac1-42a5-ba8b-6fdfd2258bc8)

### What code / cli command are you executing?
For example: I am running
```
YouTubeTranscriptApi.get_transcript ...
```

### Which Python version are you using?
`Python 3.12.2`

### Which version of youtube-transcript-api are you using?
`youtube-transcript-api 0.6.2`

# Expected behavior
 I expected to receive the transcript

# Actual behaviour
```
TranscriptsDisabled: 
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=BAW_RFcFmIU! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
```

**Comment by jdepoix** [comment]
Hi @ideepankarsharma2003, 
this is most likely due to #303. Have a look at the discussion in that issue to find out about solutions.
