### ISSUE TITLE
Failed to get English transcripts for video-id=5vTyu4ikL0I

### ISSUE THREAD

**Issue by olnrao** [jdepoix/youtube-transcript-api#315]
DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# To Reproduce

Usually when we go to YouTube site, "Show transcript" button, inside the video description panel, is a hint that transcripts are available for download. For the video url URL: https://www.youtube.com/watch?v=5vTyu4ikL0I, we see that transcripts are available and we can see it too using "Show transcripts" button.

### What code / cli command are you executing?
```
URL: https://www.youtube.com/watch?v=5vTyu4ikL0I
transcript_records = YouTubeTranscriptApi.list_transcripts(video_id="5vTyu4ikL0I", languages=["en","en-GB","en-IN"])
```

### Which Python version are you using?
Python 3.9.14

### Which version of youtube-transcript-api are you using?
youtube-transcript-api==0.6.1

# Expected behavior
Expected to get english transcripts.

# Actual behaviour
Instead I received the following error message:
```
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=5vTyu4ikL0I! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
```

**Comment by olnrao** [comment]
Thanks for the super fast response, @jdepoix.

Things have been working quite fine for an year plus now with many many videos. This _particular video_ seems to be failing.

**Comment by jdepoix** [comment]
Okay, is the code you provided the actual code you are running? Because in the code you provided you use the `language` param in `list_transcripts`, which this method does not have.

**Comment by olnrao** [comment]
Pardon me for the delayed replies, @jdepoix. Wrong truncation of the code, the API code in detail is:

# Get transcript using the YouTube Transcript API
```
try:
    video_id="5vTyu4ikL0I"
    languages=["en","en-GB","en-IN"]
    transcript_records = YouTubeTranscriptApi.get_transcript(video_id, languages=languages)
except Exception as e:
   logger.exception(f"GetTranscripts failed! Exception = {str(e)}")
    # Search for non-english transcripts
    transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)
    if len(transcript_list._manually_created_transcripts) > 0:
        language = list(transcript_list._manually_created_transcripts.keys())[0]
        transcript_records = YouTubeTranscriptApi.get_transcript(video_id, languages=[language])
    elif len(transcript_list._generated_transcripts) > 0:
        language = list(transcript_list._generated_transcripts.keys())[0]
        transcript_records = YouTubeTranscriptApi.get_transcript(video_id, languages=[language])
    else:
        raise InvalidVideoError("No transcript found in any language for the given video.")
```

Seems like the same video, same code is not reproducing the issue anymore. Not sure why it happened on that day consistently multiple times, both for me and also our customer. So, closing this.

If I hit the error again, will reach out. Thanks a lot for jumping into replying right away. Really appreciate it. Have a wonderful day.
