### ISSUE TITLE
Subtitles are disabled for this video

### ISSUE THREAD

**Issue by jsbilgi** [jdepoix/youtube-transcript-api#319]
DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# To Reproduce
All steps from SETUP.md till III (Extract and store data) worked fine. However it failed while executing `make document_store'

Have tried to using proxy like - proxies={"https": "http://localhost:8080"}. Not sure it is the correct way of using or not.

### What code / cli command are you executing?
make document_store
For example: I am running
```
YouTubeTranscriptApi.get_transcript ...
```
### Which Python version are you using?
Python 3.10.12

### Which version of youtube-transcript-api are you using?
youtube-transcript-api 0.6.2

# Expected behavior
Describe what you expected to happen. 
command executed successfully and store data in mongo database

For example: I expected to receive the english transcript

# Actual behaviour
Describe what is happening instead of the **Expected behavior**. Add **error messages** if there are any. 
Process failed after dropping database.

For example: Instead I received the following error message:
```
# ... error message ...
```

**Comment by jdepoix** [comment]
Hi @jsbilgi, please read through #303 to find more information on this issue. Closed as it is a duplicate.
