### ISSUE TITLE
TypeError: Object of type Transcript is not JSON serializable

### ISSUE THREAD

**Issue by Bluscream** [jdepoix/youtube-transcript-api#325]
DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# To Reproduce
try formatting

### What code / cli command are you executing?
![librewolf_yt1Ldm0jpR](https://github.com/user-attachments/assets/1e6df432-aaf2-441c-b600-97b425d6ad4b)

### Which Python version are you using?
Python 3.13.0a5

### Which version of youtube-transcript-api are you using?
youtube-transcript-api 0.6.2

# Expected behavior
a json string containing the transcript

# Actual behaviour
funny exception python go brrrr

For example: Instead I received the following error message:

![librewolf_afbqr7OwUW](https://github.com/user-attachments/assets/1a394c9e-b398-4767-85f6-e3faa9c6af92)

**Comment by jdepoix** [comment]
Hi @Bluscream,
you are trying to call `format_transcript` on a `Transcript` object, which does not work. You'll have to pass in the fetched transcript instead. `fmt.format_transcript(raw)` should work in your example.
