### ISSUE TITLE
Can not query multiple videos ( returns always false)

### ISSUE THREAD

**Issue by cemaytekin** [jdepoix/youtube-transcript-api#34]
Hello, for a single video id I am able to get the subtitles however if that single video id is in a bunch of video ids and I want to perform :
 jsonobject=(YouTubeTranscriptApi.get_transcript(id_list[i]))
 even though that particular video id is in the list, it returns false for all the video ids as though none of them has a subtitle.

**Comment by jdepoix** [comment]
Please provide more information on the surrounding code and which version of this module you are using. Make sure that you are using the latest version (v0.1.9), as YouTube recently changed somethings with their webclient.

**Comment by cemaytekin** [comment]
Thanks for the quick reply. It seems that when I am using VPN the code does not work however when I remove VPN, it seems fine for now.
