### ISSUE TITLE
Could not retrieve transcripts error

### ISSUE THREAD

**Issue by mounishaa-k** [jdepoix/youtube-transcript-api#341]
DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# To Reproduce
What code / CLI command are you executing?
I am running:
YouTubeTranscriptApi.get_transcript('video_id')
Which Python version are you using?
Python 3.11.9

Which version of youtube-transcript-api are you using?
youtube-transcript-api 0.6.2

Expected behavior
I expected to receive the English transcript for the video.

Actual behavior
Instead, I received the following error message:
TranscriptsDisabled: Could not retrieve a transcript for the video https://www.youtube.com/watch?v=VKFj6C-AlBo4usMA! This is most likely caused by: Subtitles are disabled for this video

**Comment by jdepoix** [comment]
Hi @mounishaa-k, the video ID you provided (`[VKFj6C-AlBo4usMA](https://www.youtube.com/watch?v=VKFj6C-AlBo4usMA)`) does not exist, therefore, you can't retrieve any transcripts for it.
