### ISSUE TITLE
Option to silence json dump when fetching transcript

### ISSUE THREAD

**Issue by aketchum15** [jdepoix/youtube-transcript-api#348]
It is very annoying to have the terminal filled with the large json response dump every time Transcript.fetch() is called. 

_extract_captions_json() has a line that prints the entire response. This seems like debug info that should not be present in the release version of the library to me. 

If it is desirable to have this dump when calling fetch(), perhaps an argument could be added to fetch to toggle the dump.

**Comment by jdepoix** [comment]
Hi @aketchum15, which version of youtube-transcript-api are you running? There's no print in `_extract_captions_json()` in the latest version (`0.6.2`) and I don't remember there ever being one tbh 🤔

**Comment by aketchum15** [comment]
I  am using version 0.6.2. After uninstalling and reinstalling the package the line is gone... I don't remember adding it, but I guess I did, oops!
