### ISSUE TITLE
Getting 401 errors on all videos Nov 25,2024

### ISSUE THREAD

**Issue by hjeffreywang** [jdepoix/youtube-transcript-api#356]
Could be a ongoing update from youtube, but today all my caption calls have been giving me errors

tested video IDs: ['e9Ne4oU7fLQ', 'ZlPdPbbwqd8', 'rR71vbzutNE', '9OH9U03U180', '4rnn52ySx18', 'D5MjRZvT8aM', 'azQ4cvTHYyQ', 'wDDSiSjxQcE']

# To Reproduce
Steps to reproduce the behavior: just call the usual script
YouTubeTranscriptApi.get_transcript(video_id)

### What code / cli command are you executing?
For example: I am running
```
 YouTubeTranscriptApi.get_transcript(video_id)
```

### Which Python version are you using?
Python 3.10

### Which version of youtube-transcript-api are you using?
youtube-transcript-api 0.6.3

# Actual behaviour

```
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=e9Ne4oU7fLQ! This is most likely caused by:

Subtitles are disabled for this video

```
Subtitles are not disabled on this video, I've tried other videos and gotten the same error

**Comment by jdepoix** [comment]
Hi @hjeffreywang, are you running this code locally or in a cloud environment? If it is run in the cloud, it is very likely to be related to #303.

**Comment by hjeffreywang** [comment]
I'll try using a different wifi. Was using hotel wifi, VPN, and local docker container. Usual stack works with VPN and docker container which leaves that wifi as the culprit. Will update once I get home from my flight

**Comment by hjeffreywang** [comment]
I fixed the error. The issue seems to stem from a update on a from a different youtube based library. Could also be a weird container interaction, but after pruning some code, it seems to have worked.

**Comment by jdepoix** [comment]
@starlacortes to find more on the issue you are describing head over to #303.

@hjeffreywang thanks for the update! I will close this now!
