### ISSUE TITLE
Could not retrieve a transcript for the video

### ISSUE THREAD

**Issue by nitesh-modi** [jdepoix/youtube-transcript-api#359]
I am using [YouTube Captions] API for getting caption but this API not working as expected.

API:-  https://youtube-captions1.p.rapidapi.com/graphql

Could not retrieve a transcript for the video :-  https://www.youtube.com/watch?v=ExcRbA7fy_A!

I am getting this error :- 
{"data":{"video":{"captions":null}},"errors":[{"locations":[{"column":5,"line":3}],"message":"\nCould not retrieve a transcript for the video https://www.youtube.com/watch?v=ExcRbA7fy_A! This is most likely caused by:\n\nSubtitles are disabled for this video\n\nIf you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!","path":["video","captions"]}]}

Please check let me know what the issue.

Thanks

**Comment by jdepoix** [comment]
Hi @nitesh-modi, this project has no association with the the API you are using. You'll have to get in contact with the maintainer of the API for them to take care of your issue. From what I can tell it looks like their IP address is being blocked.

**Comment by nitesh-modi** [comment]
But the API response says: 'Please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues.'

**Comment by jdepoix** [comment]
Because this API apparently is implemented using this module and the maintainer just forwarded this error message to the user. The underlying issue is already being discussed in #303. But there is nothing that you or I can do to fix this, the maintainer of that API has to take care of it.
