### ISSUE TITLE
ImportError: cannot import name 'YouTubeTranscriptApi' from partially initialized module 'youtube_transcript_api' (most likely due to a circular import) 

### ISSUE THREAD

**Issue by vinodyk** [jdepoix/youtube-transcript-api#44]
ImportError: cannot import name 'YouTubeTranscriptApi' from partially initialized module 'youtube_transcript_api' (most likely due to a circular import)

**Comment by jdepoix** [comment]
@vinodyk could you please provide more information on what you are trying to do?

It seems that you have a circular import in your code, as the error message suggests, but there's no way to help you if you just dump an error message here without any context...

**Comment by vinodyk** [comment]
Thanks for quick response.
Figured it out, I had the code in file saved as `_youtube_transcript_api.py`_ so it was loading this file instead of expected module.

**Comment by vinodyk** [comment]
thanks
