### ISSUE TITLE
Allow for Age Restricted Videos to be Accessed

### ISSUE THREAD

**Issue by danielcliu** [jdepoix/youtube-transcript-api#45]
If you try to access an age-restricted video, like `GU7qYaYzd-0`, without cookies you get back the `The video is no longer available` error. There should be functionality added to allow a user to load their Youtube cookies so they have the authorization required to access the age-restricted video. 

I have almost finished a small PR to complete this, so if you're ok with it I will open up said PR.

**Comment by jdepoix** [comment]
Hi @danielcliu,
thanks for the report. Looking forward to the PR! 😊👍 
But doesn't fixing this require some sort of login?

**Comment by danielcliu** [comment]
It requires the user to be able to have access to the desired video through web-browser.

**Comment by jdepoix** [comment]
Okay, that seems like an easy fix, as all requests are already done using a Session object.

**Comment by jdepoix** [comment]
This has just been released as part of v0.3.0. Thank you for the contribution! 😊
