### ISSUE TITLE
cli tool is referred but is missing 

### ISSUE THREAD

**Issue by CoolCold** [jdepoix/youtube-transcript-api#48]
Hello!
Docs refers usage of CLI tool, but the tool itself is not provided. For example after `pip install youtube_transcript_api` , dir contents is:
```
coolcold@LAZ-VN-L-W-2202:~$ tree ./.asdf/installs/python/3.8.1/lib/python3.8/site-packages/youtube_transcript_api
./.asdf/installs/python/3.8.1/lib/python3.8/site-packages/youtube_transcript_api
├── __init__.py
├── __main__.py
├── __pycache__
│   ├── __init__.cpython-38.pyc
│   ├── __main__.cpython-38.pyc
│   ├── _api.cpython-38.pyc
│   ├── _cli.cpython-38.pyc
│   ├── _errors.cpython-38.pyc
│   ├── _html_unescaping.cpython-38.pyc
│   ├── _settings.cpython-38.pyc
│   └── _transcripts.cpython-38.pyc
├── _api.py
├── _cli.py
├── _errors.py
├── _html_unescaping.py
├── _settings.py
├── _transcripts.py
└── test
    ├── __init__.py
    ├── __pycache__
    │   ├── __init__.cpython-38.pyc
    │   ├── test_api.cpython-38.pyc
    │   └── test_cli.cpython-38.pyc
    ├── assets
    │   ├── __init__.py
    │   └── __pycache__
    │       └── __init__.cpython-38.pyc
    ├── test_api.py
    └── test_cli.py

5 directories, 24 files
```

**Comment by jdepoix** [comment]
I am not sure what you are searching for in this directory. The `__main__.py` is the file which is executed when you run `youtube_transcript_api ...`. 
I am not sure what system you are using but the the executable will most likely be located under `.../python/3.8.1/bin/youtube_transcript_api`. Either way it should be added to your path by pip so you don't have to know the executables exact location. Just run `youtube_transcript_api ...` in your terminal.
