### ISSUE TITLE
Google Colab issue

### ISSUE THREAD

**Issue by benjackman** [jdepoix/youtube-transcript-api#50]
Hi jdepoix!

Thanks for a fantastic API. I've found it very useful. 

I have noticed a strange bug though (and it may not be related to your code). I cannot get this API to work run on Google Colab. It works fine in a local environment for this video: 

https://www.youtube.com/watch?v=_S2lYXf-uu0 (video ID: _S2lYXf-uu0)

But the same video returns a VideoUnavailable error when run on Google Colab. Both environments are running youtube-transcript-api 0.3.1.

Do you have any idea why this might be? I am happy for this to be closed if you aware of this as a separate issue unrelated to your codebase etc, or think it would be unrelated, or can't help, etc.

Thanks again
Ben

**Comment by jdepoix** [comment]
Hi Ben,
I just tried this in a colab notebook (https://colab.research.google.com/drive/1MMlkYhdSSLC6fCq5UXmqBJnNGAyjHRSh) and I have no issues getting the transcript. Looks like this is something specific to your notebooks environment.
Cheers,
Jonas

**Comment by benjackman** [comment]
Thanks Jonas! Not sure what the issue was yesterday - I was able to get it all working now. Sorry for bothering!
