### ISSUE TITLE
Only get videos by language

### ISSUE THREAD

**Issue by leonardltk** [jdepoix/youtube-transcript-api#55]
Hi, this is a wonderful api.

Just wondering, is there a way for me to only get videos by a specific language ?

For example, today i only want to download random videos with manual english subtitles, (hence video is in english too).

Tomorrow i only want to download transcript with manual mandarin transcripts, (hence video is in chinese too).

**Comment by jdepoix** [comment]
Hi @leonardltk,
I am not sure if I am understanding you correctly. You just want random videos for a given language, without providing a video id? If that's the case, no that is not possible, you'll always have to provide a video id for the video you want to retrieve. You could have a look at the official YouTube API, maybe it allows iterating over random videos (and then use this module to get the transcript), but I highly doubt that.

**Comment by jdepoix** [comment]
@leonardltk please let me know if this answers your question, so that I can close this issue.

**Comment by leonardltk** [comment]
Yes, maybe asking for random videos is abit asking for too much. 

How about, listing all videos in a channel ?

So that given a known channel, i can iterate this list and perform the transcription.

**Comment by jdepoix** [comment]
@leonardltk I am pretty sure that this functionality is already covered by the official YouTube API. Therefore, I don't see a need to implement it into this module.

**Comment by leonardltk** [comment]
Got it, thanks.
