### ISSUE TITLE
VideoUnavailable problem for available video

### ISSUE THREAD

**Issue by pva22** [jdepoix/youtube-transcript-api#56]
I use: 

```
from youtube_transcript_api import YouTubeTranscriptApi
YouTubeTranscriptApi.get_transcript(video_id)
```

Get this error:
> 
VideoUnavailable: 
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=ppWPuXsnf1Q! This is most likely caused by:

The video is no longer available

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!

>

**Comment by jdepoix** [comment]
I can not replicate the error for the video ppWPuXsnf1Q. I can retrieve the transcripts for this video without a problem. Looks like it's a problem on your end. Maybe a connection issue? Can you get the transcript you are looking for when you open the video in the browser? Sometimes transcript are temporarily not available. Maybe just give it another try and let me know how it goes.

**Comment by joacosaralegui** [comment]
Hey i sometimes get this error when using the api to much in a short period of time! Usually Youtube seems to ban those IP addresses. I overpass this by changing the IP in which my server is running, but im sure there must be a more elegant solution!

**Comment by jdepoix** [comment]
@joacosaralegui I've previously had a few people report that they get errors when executing a lot of requests in a short period of time. Personally I was never able to replicate this, even with high amounts of requests, but it makes sense that YouTube would block a certain IP if they send in to many requests. But I don't see how this module could do anything about this. Any suggestions?

**Comment by jdepoix** [comment]
I will close this now, as I don't see a fixable Issue here. But feel free to add suggestions on how to improve upon this @joacosaralegui
