### ISSUE TITLE
Script is broken

### ISSUE THREAD

**Issue by deniswsrosa** [jdepoix/youtube-transcript-api#58]
Hi, I just tried to reinstall everything and  seems like there is something wrong with the latest version:
`  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/youtube_transcript_api/__init__.py", line 1, in <module>
    from ._api import YouTubeTranscriptApi
  File "/Library/Python/2.7/site-packages/youtube_transcript_api/_api.py", line 4, in <module>
    CookieLoadError = (FileNotFoundError, cookiejar.LoadError)`

I can't use it via line command or on my python script

**Comment by danielcliu** [comment]
I'll look into this later today

**Comment by jdepoix** [comment]
@deniswsrosa I just tried this and I can not replicate it. Could you please provide the exact python and youtube-transcript-api versions you are using?

**Comment by danielcliu** [comment]
I was unable to replicate also

**Comment by jdepoix** [comment]
@deniswsrosa were you able to fix this? Can you provide more information? Otherwise I will close this issue.

**Comment by deniswsrosa** [comment]
Hi, Actually I just noticed that the problem with my code was something else (I tried to run it on my terminal but it was running python 2,7). The actual error is:

```
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=https://www.youtube.com/watch?v=CZ3wIuvmHeM! This is most likely caused by:

The video is no longer available
```

when I run  **youtube_transcript_api https://www.youtube.com/watch?v=CZ3wIuvmHeM** , but the video is available. Is there anything missing?

**Comment by jdepoix** [comment]
you have to run `youtube_transcript_api CZ3wIuvmHeM`

**Comment by deniswsrosa** [comment]
I'm an idiot
