### ISSUE TITLE
I can't get transcripts with age restrictions. 

### ISSUE THREAD

**Issue by RomanTerentiev** [jdepoix/youtube-transcript-api#59]
Hello. I Can't get transcription with age restrictions. For example videoID = thsHOAF7LQI

**Comment by danielcliu** [comment]
Hello RomanTerentiev,

I am unable to replicate your error. I was able to get the transcript for ` thsHOAF7LQI` in both python 2.7 and 3.6.9 on the latest version of `youtube-transcript-api`

You are using cookies right? For age restricted videos you must have a Youtube account that can access the video in browser, then download your cookies into a text file. See the `Cookies` section in the ReadMe. 

If you are using cookies correctly in your `get_transcript` call, then I will need more information on what python version and `youtube-transcript-api` version you are using.

**Comment by RomanTerentiev** [comment]
Oh.... Thank you. I wrote a module for my project so long ago that I forgot about cookies ...

Have a nice day :)
