### ISSUE TITLE
Preferred language support

### ISSUE THREAD

**Issue by sebbnet** [jdepoix/youtube-transcript-api#6]
Hi, I noticed that someone opened up another post with regards to restricting the language to be English. I am also looking for this functionality. The video linked by Sundaresh, `GJLlxj_dtq8` has transcripts in many languages, but it seems that the script pulls the text for the language that is listed first alphabetically, in this case it would be in Chinese. I am wondering if the API has changed since 6 months ago?

And so, I think it would help myself and many users you could look into whether functionality could be added such that an array of preferred languages may be passed and it retrieves the transcript based on whether it is available in those languages, e.g. [english, korean, russian] --> not found in english, found in korean ==> korean output. If none of the preferred languages are found, output text for any language, otherwise throw the 'no transcript error'. 

Thanks for the great repo!

**Comment by jdepoix** [comment]
Thank you for you suggestion! I implemented the feature in #7 and just published is in a new version (0.1.2).

I added the following section to the README, which describes how it works:

You can also add the languages param if you want to make sure the transcripts are retrieved in your desired language (it usually defaults to english).

YouTubeTranscriptApi.get_transcripts(video_ids, languages=['de', 'en'])
It's a list of language codes in a descending priority. In this example it will first try to fetch the german transcript ('de') and then fetch the english transcipt ('en') if it fails to do so. As I can't provide a complete list of all working language codes with full certainty, you may have to play around with the language codes a bit, to find the one which is working for you!
