### ISSUE TITLE
Transcripts not available

### ISSUE THREAD

**Issue by ccrupp** [jdepoix/youtube-transcript-api#61]
I used this library yesterday and was able to access a multitude of transcripts. However, when I try to use the library today, it says that it could not retrieve the transcript most likely because: the video is no longer available when it is. Did something change or am I doing something wrong?

**Comment by jdepoix** [comment]
Hi @ccrupp. I can not replicate this error. Which python version are you using? And are you sure it's not a network issue on your end?

**Comment by ccrupp** [comment]
Thanks for the response @jdepoix! I'm currently using Python 3.8.3, I don't believe it's a network issue on my end because I can access the video through my browser just fine. My thought is that I created too many requests but the rate limit is reset daily for the youtube API but it is still not working for me after waiting a day. Is this a common problem? I've tried with many other videos with no luck

**Comment by danielcliu** [comment]
@ccrupp Just to case you thought otherwise, this library does not use the Youtube Data V3 API so there is no "Quota" reset every day

**Comment by ccrupp** [comment]
Oh good to know, however, I'm more confused now. Any suggestions as to what I should try differently? I'm kind of at a loss for solutions

**Comment by danielcliu** [comment]
I am unsure and unable to investigate further right now. Rate limiting has been an issue before with this library and so maybe there are some solutions in the other threads? I would check out https://github.com/jdepoix/youtube-transcript-api/issues/60 for starters

**Comment by ccrupp** [comment]
Thank you, I will check them out. I'll close this thread for now
