### ISSUE TITLE
Fetch video title

### ISSUE THREAD

**Issue by joacosaralegui** [jdepoix/youtube-transcript-api#62]
Hi! I was looking for a way to retrieve the video title but couldn't find one. Is there a way to achieve this that im missing? I know its not the purpouse of these API but It may be cool if it could so i dont have to get also youtube-dl or something like that only for the video title.
Thanks!!

**Comment by jdepoix** [comment]
Hi @joacosaralegui,
the standard YouTube API should be able to give you that information. I don't think that replicating functionality, which is already covered by other modules just for convenience is a good idea, nor is it necessary. I'd like to keep the scope of this module as it is, or at least only expand it if there's a feature which is not already covered by others.
