### ISSUE TITLE
The video is no longer available WITH ANY VIDEO

### ISSUE THREAD

**Issue by SnoopiACK** [jdepoix/youtube-transcript-api#65]
I had used youtube_transcript_api without problem a lot of time.
A couple days ago I upgraded my python to 3.8.  the library still worked for few hours but after that started to crash and don't work with any id_video.

the error show "The video is no longer available"  with any available video. 

youtube-transcript-api             0.3.1

  File "<ipython-input-4-1a6984acc630>", line 1, in <module>
    transcript_list = YouTubeTranscriptApi.list_transcripts(v_id)

  File "C:\Users\SnooPI\Anaconda3\lib\site-packages\youtube_transcript_api\_api.py", line 70, in list_transcripts
    return TranscriptListFetcher(http_client).fetch(video_id)

  File "C:\Users\SnooPI\Anaconda3\lib\site-packages\youtube_transcript_api\_transcripts.py", line 34, in fetch
    self._extract_captions_json(self._fetch_html(video_id), video_id)

  File "C:\Users\SnooPI\Anaconda3\lib\site-packages\youtube_transcript_api\_transcripts.py", line 42, in _extract_captions_json
    raise VideoUnavailable(video_id)

**Comment by jdepoix** [comment]
I can not replicate this using python 3.8.1, so it doesn't seem to be a problem with the python version. So you get the same error for every video id you try?
Maybe try setting up a fresh virtualenv, install the module and see how that goes.

**Comment by SnoopiACK** [comment]
> I can not replicate this using python 3.8.1, so it doesn't seem to be a problem with the python version. So you get the same error for every video id you try?
> Maybe try setting up a fresh virtualenv, install the module and see how that goes.

I'm thinking that this is a "I'm not a robot" problem, I'll try using a proxy or something like that

**Comment by bjbroder** [comment]
I'm having what I believe is the same issue - videos that I was able to get transcripts for yesterday, now no longer work ("The video is no longer available"). I haven't done any sort of updates in that time. Has a fix been found?

youtube-transcript-api version: 0.3.1
python version: 3.7.4

**Comment by jdepoix** [comment]
In that case have a look at #60, there already is a discussion about YouTube rate limits. However, unfortunately there isn't really anything we can do about this.
