### ISSUE TITLE
Requests limits?

### ISSUE THREAD

**Issue by free-burger** [jdepoix/youtube-transcript-api#66]
Does this method has any limitations? I made a loop and after 250 requests it returns: 

_VideoUnavailable: 
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=xxxxx! This is most likely caused by:

The video is no longer available

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!_

**Comment by jdepoix** [comment]
Many users have reported that they ran into rate limits. However, this doesn't seem to be consistent. In the past I have been able to loop over more than 10k YouTube videos and get their transcripts without running into any issues, while others report being limited after a few hundred videos like you.

Check out #60 so read more about it, but unfortunately there isn't anything we can do here.
