### ISSUE TITLE
getting error for unavalable for language code for video, while list shows code is available

### ISSUE THREAD

**Issue by CoolCold** [jdepoix/youtube-transcript-api#67]
I did start with the example provided (it actually is missing "import .." part), code:
```
# retrieve the available transcripts
from youtube_transcript_api import YouTubeTranscriptApi

video_id='77rjqnNsP8Q'
transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)

# iterate over all available transcripts
for transcript in transcript_list:

    # the Transcript object provides metadata properties
    print(
        transcript.video_id,
        transcript.language,
        transcript.language_code,
        # whether it has been manually created or generated by YouTube
        transcript.is_generated,
        # whether this transcript can be translated or not
        transcript.is_translatable,
        # a list of languages the transcript can be translated to
        transcript.translation_languages,
    )

    # fetch the actual transcript data
    print(transcript.fetch())

    # translating the transcript will return another transcript object
    print(transcript.translate('en').fetch())

# you can also directly filter for the language you are looking for, using the transcript list
transcript = transcript_list.find_transcript(['ru', 'en'])

# or just filter for manually created transcripts
transcript = transcript_list.find_manually_created_transcript(['ru', 'en'])

# or automatically generated ones
transcript = transcript_list.find_generated_transcript(['ru', 'en'])
```
and I got error:

```
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=77rjqnNsP8Q! This is most likely caused by:

No transcripts were found for any of the requested language codes: ['ru', 'en']

For this video (77rjqnNsP8Q) transcripts are available in the following languages:

(MANUALLY CREATED)
None

(GENERATED)
 - en ("English (auto-generated)")[TRANSLATABLE]

(TRANSLATION LANGUAGES)
 - af ("Afrikaans")
 - sq ("Albanian")
 - am ("Amharic")
 - ar ("Arabic")
...
 - pa ("Punjabi")
 - ro ("Romanian")
 - ru ("Russian")
 - sm ("Samoan")
 - gd ("Scottish Gaelic")
...
 - zu ("Zulu")

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api yo
u are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
```

What I don't understand is, the output
a) states cannot find EN or RU
b) lists EN and RU as available

one of this options is false or my hands are curved too much?

```
pip list|fgrep youtube && python --version
youtube-transcript-api 0.3.1
Python 3.8.1
```

**Comment by jdepoix** [comment]
The error is raised because you are calling find_manually_created_transcripts. As the error message shows, there are no manually created transcripts. The find_generated_transcript call will not fail, as a en transcript is available. ru is only listed as a translation language not as a transcript language. Please read the docs on this. So everything is working as it should be.

Regarding the import in the example: I disagree that this example should be something which you just copy/paste and it works. It’s an example and not a template. It’s supposed to showcase how you could use some of the methods together, not to provide a template so you don’t have to code anything.

**Comment by CoolCold** [comment]
@jdepoix thanks for explanation, sorry for taking your time on this.

Regarding import: my expectations from the guides and samples that it will work when you follow it step by step, using exact code being run by author. Providing **example** which is known to fail from the beginning doesn't make sense to me.

Seeing something "Example, adjust it to your needs/proper python code" would dissolve any confusion (it will still look strange, but at least not confused why it's not working when you do exactly the same steps as author)
