### ISSUE TITLE
Could not retrieve a transcript for the video although it exists.

### ISSUE THREAD

**Issue by amuuu** [jdepoix/youtube-transcript-api#69]
Hi!
I get an error that says:
```
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=[ANY ID]! This is most likely caused by:
The video is no longer available.
```
I checked with a couple other videos and they have captions, but I get the same error.

**Comment by jdepoix** [comment]
Hi @amuuu,
So the error happens for every video you try? How many videos did you try to retrieve? Some users have reported running into rate limits. Check out #60 to read more on rate limits.

**Comment by amuuu** [comment]
I guess it was a problem caused by YouTube API. I checked it again today, and it works perfectly. I think I was trying to get a large number of videos in a short time and the API blocked my IP or something. It's good to put some delay in between videos when getting the transcripts.
