### ISSUE TITLE
Error every time I call YouTubeTranscriptApi.get_transcript

### ISSUE THREAD

**Issue by vslater** [jdepoix/youtube-transcript-api#77]
This has been working normally for me but now every time I try to use this I get this error:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    val = YouTubeTranscriptApi.get_transcript('h-wfO6_eq-A')
  File "/Library/Python/3.7/site-packages/youtube_transcript_api/_api.py", line 128, in get_transcript
    return cls.list_transcripts(video_id, proxies, cookies).find_transcript(languages).fetch()
  File "/Library/Python/3.7/site-packages/youtube_transcript_api/_api.py", line 70, in list_transcripts
    return TranscriptListFetcher(http_client).fetch(video_id)
  File "/Library/Python/3.7/site-packages/youtube_transcript_api/_transcripts.py", line 34, in fetch
    self._extract_captions_json(self._fetch_html(video_id), video_id)
  File "/Library/Python/3.7/site-packages/youtube_transcript_api/_transcripts.py", line 42, in _extract_captions_json
    raise VideoUnavailable(video_id)
youtube_transcript_api._errors.VideoUnavailable: 
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=h-wfO6_eq-A! This is most likely caused by:

The video is no longer available

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!

This is using Version: 0.3.1

**Comment by jdepoix** [comment]
Hi @vslater,
is this independent of the video id you are trying to get a transcript for? If so, you might be running into rate limits (see #60 for more information on that).

Could you please try it again and if it still fails execute the following and upload the results somewhere so that I can have a look at it:
```
curl -L "https://www.youtube.com/watch?v=h-wfO6_eq-A"
```

**Comment by jdepoix** [comment]
Any news on this @vslater? Otherwise I will close this issue.
