### ISSUE TITLE
Possible to provide other request info to the YouTubeTranscriptApi.get_transcript() method?

### ISSUE THREAD

**Issue by iblind** [jdepoix/youtube-transcript-api#82]
In trying to debug #79, I began to wonder if it's possible that certain header data may be being transmitted with the call. 

I then started wondering if it's possible to change certain aspects of the header, since I think I may have read in another issue thread that the `get_transcript()` call is a wrapper for the `requests.get()` — is that the case? 

So in this case, would it be possible to work with the `YouTubeTranscriptApi.get_transcript()` method in the same way as working with the `requests.get()` method? 

And, does that consequently mean that you can also change the cookies values/do other things that you can with requests (sorry if this is in the docs, I hadn't seen it if so)?

**Comment by jdepoix** [comment]
Yes, `get_transcript()` uses the requests module. However, those options you asked about are not accessible via the public API, as they are not needed in "normal usage". Just to be clear, you just need this for debugging, not for normal usage of this module, right?
For debugging you are probably best of to just clone this repository and modify it where needed, if you want to mess around with different headers. The code base is fairly small and simple, just have a look. Actually there's only two places where requests are happening which are: `_transcripts.Transcript.fetch()` and `_transcripts.TranscriptListFetcher._fetch_html(...)`
