### ISSUE TITLE
The get_transcript method is not working in production.

### ISSUE THREAD

**Issue by iamprayush** [jdepoix/youtube-transcript-api#85]
I'm using the `get_transcript` method in my Django app that I've deployed using [pythonanywhere](pythonanywhere.com/), but the method is raising the `VideoUnavailable` error, even though the same script is working fine locally.

**Comment by danielcliu** [comment]
I am not offhand sure what is going wrong for you, but it seems like it may be related to #60. Basically Youtube may be rate limiting pythonanywhere's IPs.

**Comment by iamprayush** [comment]
I see, I guess I'll have to choose a different hosting platform. Thanks, @danielcliu!
