### ISSUE TITLE
Migrate to Travis-ci.com

### ISSUE THREAD

**Issue by danielcliu** [jdepoix/youtube-transcript-api#87]
https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com

Via this, it seems like travis-ci.org will be deprecated on December 31, 2020. So this probably needs to be migrated sooner or later to travis-ci.com

**Comment by jdepoix** [comment]
Hi @danielcliu,
thanks for pointing this out! I took care of this in #88.
