### ISSUE TITLE
Error: The video is no longer available

### ISSUE THREAD

**Issue by panliu87** [jdepoix/youtube-transcript-api#89]
Hi, I am using the API to download transcript of videos and it works well. But when I use it today, it keeps saying "The video is no longer available". But I am sure the video is there and it has transcript. 

Some video IDs are: XYNsWqnocl8, MLw_lq03eww, G_uiYrhbwbQ, Eq3zPFnxNwI, etc.

Any suggestions on how to fix this?

**Comment by jdepoix** [comment]
Hi @panliu87,
if you are running into problems were you suddenly are not able retrieve videos which you were able to retrieve before on the same machine (or which should be available), you are most likely running into rate limits. Have a look at #60 to read more about this. 
Is the machine which is doing the requests hosted on any cloud platform?

**Comment by jdepoix** [comment]
@panliu87 you might be able to help me to help you by executing the following and uploading the results (Doesn't have to be done with curl, I just need to see what the request to YouTube returns):
```
curl 'https://www.youtube.com/watch?v=XYNsWqnocl8'
```
Please make sure the requests is still failing while using this module before executing the request manually.

**Comment by jdepoix** [comment]
Hi @panliu87, any news on this?

**Comment by jdepoix** [comment]
Closed due to inactivity.
