### ISSUE TITLE
Youtube transcript cannot be fetched using youtube transcript API 0.3.1 python

### ISSUE THREAD

**Issue by SumanMarahatha7** [jdepoix/youtube-transcript-api#91]
It prompts following error:
![Screenshot (58)](https://user-images.githubusercontent.com/50476717/101274325-3b6cc080-37c5-11eb-98da-d1f6b6339e91.png)

VideoUnavailable at /search/
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=TBYIki-pMNI! This is most likely caused by:

The video is no longer available

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!

Screenshots of error are attached below

**Comment by jdepoix** [comment]
Retrieving the transcript for TBYIki-pMNI works for me. DId you happen to execute many requests at once, or in a short period of time? If so you might be running into rate limits, see #60 and #74 for more on this.
Is this happening for all videos you are trying to get a transcript for or only TBYIki-pMNI?

**Comment by jdepoix** [comment]
Any news on this @SumanMarahatha7? Otherwise I will close this issue.

**Comment by jdepoix** [comment]
Closed due to inactivity
