### ISSUE TITLE
No module named 'youtube_transcript_api'

### ISSUE THREAD

**Issue by lululy** [jdepoix/youtube-transcript-api#92]
I am trying to run youtube_transcript_api in Jupyter. However, I keep getting an error showing 
```
ModuleNotFoundError: No module named 'youtube_transcript_api'
```
I have installed it using 
```
pip install youtube_transcript_api
```
I also checked the file is under the python folder--site-packages on my laptop. So it seems like the module has been installed.
I'm still new to python, so maybe it's a stupid question. Appreciate if any help! Thank you!

**Comment by jdepoix** [comment]
Hi @lululy,
can you use other module inside the notebook, which you have installed using pip?
This doesn't look like a problem with this module, but with your Jupyter setup, therefore I'll close this issue.
It's hard to say what the exact problem is without knowing your setup, so a few hints that come to mind:
* Are you using a virtualenv? If so, is jupyter running in the same env you install this module in?
* On a similar note (in case you're not using venv), did you install/run jupyther for another python version than this module?
