### ISSUE TITLE
Information ASR functioning

### ISSUE THREAD

**Issue by CamilleSchr** [jdepoix/youtube-transcript-api#96]
Hello,
Thank you for your work, it works pretty well ! :)

I just have a technical question on how the automatic speech recognition works on this Youtube transcript api, is it using an acoustic and language model ? Is BERT the language model use for it ? 
I searched for documentation but I didn't find anything, if you have papers, I'm interested.

Thanks !
Camille

**Comment by jdepoix** [comment]
Hi @CamilleSchr,
this module just retrieves the subtitles which have automatically been generated by YouTube. I don't think that information on how YouTube generates those is publicly available.
