### ISSUE TITLE
Same error on every video id since yesterday: VideoUnavailable

### ISSUE THREAD

**Issue by Dragonum314** [jdepoix/youtube-transcript-api#97]
Hi, thanks for the great API!

Since yesterday I get the same error for every call I make to the API. 
With any youtube video ID i get 

```
VideoUnavailable: 
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=H2EaqTk4wbI!! This is most likely caused by:

The video is no longer available
```

Steps to reproduce: 
```
from youtube_transcript_api import YouTubeTranscriptApi
transcript_tracks = YouTubeTranscriptApi.list_transcripts('H2EaqTk4wbI!')
```

I'm on Catalina 10.5.5, python 3.8.5, youtube-transcript-api 0.3.1

Thanks again for the work

**Comment by jdepoix** [comment]
Hi @Dragonum314, you are most likely being rate limited by YouTube. There unfortunately is not much we can do here. check out #60 if you want to read more on this.
However, @kovan has just submitted the PR #94 which adds an error message specific to this case. So in future version you'll at least know that this is what's happening.

**Comment by kurtabela** [comment]
Same issue here. This wasn't here a few months ago, and I just tried this for the first time in a long time. Don't know, never had this error before

**Comment by jdepoix** [comment]
@kurtabela What version of youtube-transcript-api are you on?

**Comment by kurtabela** [comment]
... I just upgraded to the latest version and it worked... :) Now I feel stupid ahah

Thanks for the great API!
